- .gitignore
- README.md
- bot/cogs/template.py
added a .gitignore file with `log/` for #5 as well as a better Readme with a lengthy getting started
#5 added .log/ to .gitignore
closes #13 
closes #14
> added .gitignore and improved readme

- bot/__init__.py
- bot/bot.py
This is what I have so far thanks
Issue: #5
> Logging Feature

- bot/cogs/halloweenify.py
- bot/resources/halloweenify.json
I scraped some images and nicknames from the web and implemented the halloweenify feature.
> Implement Halloweenify feature.

- bot/cogs/spookyreact.py
Add cog for reacting to certain messages containing words such as: spooky, skeleton, danger, etc.
Each 'trigger' maps to a certain pre-defined emoji.
So far implemented: :ghost:, :jack_o_lantern:, :skull:, :skull_and_crossbones:
> Fix #27: Add spooky reactions.

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Hello,
I hope this is an adequate pull requst template.
😸
> Issue #15 Feature pull request template

- bot/cogs/error_handler.py
Just added a simple error handler, if you spot anything that you would like to change just tell me :)
> Added a error handler!

- bot/cogs/hacktober/hacktoberstats.py
- bot/cogs/hacktober/halloweenify.py
- bot/cogs/hacktober/monstersurvey.py
- bot/cogs/hacktober/scarymovie.py
- bot/cogs/hacktober/spookyavatar.py
- bot/cogs/hacktober/spookygif.py
- bot/resources/halloween/monstersurvey.json
Went through the hacktober cogs and added the `with_typing()` context manager where appropriate.
Fixed some minor syntax issues & cleaned some syntax where immediately noticeable.
Resolves #68
> Typing context manager for Hacktober cogs

- bot/__init__.py
- bot/constants.py
- bot/seasons/christmas/__init__.py
- bot/seasons/evergreen/__init__.py
- bot/seasons/halloween/__init__.py
- bot/seasons/halloween/spookyreact.py
- bot/seasons/season.py
Contributing to address points made in [this comment](https://github.com/python-discord/seasonalbot/pull/64#issuecomment-440475439) for the pending #64 PR.
> Refine Season Systems, with focus on ratelimit considerations and debug mode.

- bot/seasons/christmas/adventofcode.py
Update member name regex to properly handle hyphens
Remove session cookie from global leaderboard request
> Fix global lb display to respect ties

- bot/seasons/christmas/adventofcode.py
This should improve the AoC countdown status (`Playing in 5 hours and 30 minutes`) by aligning the status changes to whole steps and make the length of these steps a constant. 
It also changes the text to something like `Playing in less than 5 minutes` if the release time is only one step or less away, and `Playing right now!` during the first step after the release. After that, for the first hour after the release, it will say something like `Playing since 25 minutes ago`. The rest of the time it still uses the old format.
> Improve countdown status (align to whole 5 minutes, better messages)

- CONTRIBUTING.md
- README.md
- bot/constants.py
- Add Lovefest role & channel IDs to bot constants
- Update environment variable name for seasonalbot (was hacktoberbot)
- Update Contributor doc to reference pipenv guide rather than the deprecated Seasonalbot GH wiki
> Add Lovefest configuration, update project documents

- bot/constants.py
- bot/resources/valentines/date_ideas.json
- bot/seasons/valentines/savethedate.py
Closes #101 
This command [prefix]savethedate ,sends out ideas for the valentines day.I have added around 30 ideas (using JSON file to store the data). More ideas can be added if needed.So when ever anyone calls this command, the bot embed the title and description of date idea and sends it.I have added nice emojis at the start and end of the description.These emojis are randomly selected from an emoji list.
Not the best of the pull requests, this is my first time 😄 
By the way this is Iceman in discord.
> Added the command savethedate.

- README.md
Accidentally missed a section explaining how to make a branch in PyCharm last time.
Also added a clear request for people to read the CONTRIBUTING.md document, as it seems it's being forgotten.
> Mention CONTRIBUTING.md, fix missing branch step.

- bot/resources/valentines/love_matches.json
- bot/seasons/valentines/lovecalculator.py
This love calculator uses two user-IDs, adds them together and takes the
modulus of 100 from it.
**Invocation:** .love [mention-user] [mention-user]
**Aliases:** .love_calculator .love_calc
> Add LoveCalculator as described in #96

- bot/seasons/valentines/movie_generator.py
closes #109 
this command goes to the TMDB API and selects random romance movie
> added command .romancemovie

- bot/seasons/evergreen/fun.py
Closes #93.
Readded fun.py file to evergreen and added roll command that rolls up to 6 dice randomly and uses the terning emotes on the discord.
> Readded fun.py file to evergreen and added roll command.

- bot/bot.py
- bot/resources/valentines/love_matches.json
- bot/seasons/valentines/lovecalculator.py
Things that have changed
- Now accepts arbitrary input in addition to members
- And therefore changed the %-age calculating method too
- Escapes discord markdown for given arguments
- __Globally__ resets cooldown on commands upon user input errors (seemed a bit harsh)
\
Things that I have to finish before merge
\
I opened the PR to get review for the actual code whilst I figure out the docstring for the command.
> Refine love calculator command

- bot/resources/valentines/zodiac_compatibility.json
- bot/seasons/valentines/valentine_zodiac.py
closes #107 
Wrote the command .partnerzodiac as described in issue #107.
So this command returns a counter compatible zodiac sign.
I have taken the 4 most compatible zodiac signs and the bot returns a random one with a compatible meter and description.
sources : 1) https://www.ganeshaspeaks.com/zodiac-signs/compatibility/
2) https://www.astrology-zodiac-signs.com/compatibility/
> Add command .partnerzodiac

- bot/seasons/evergreen/error_handler.py
- bot/seasons/valentines/savethedate.py
1)Added a help text to .savethedate
2)Edited the error message for cooldowns so that it shows not only seconds remaining but also minutes(if cooldowntime>60 seconds)
> added help message for .savethedate and edited the error_message for cooldown error

- bot/resources/valentines/pickup_lines.json
- bot/seasons/valentines/pickuplines.py
---
name: Pickup Lines
about: The cheesy pickup lines for the Valentine's Day Season
issue: #125 
---
This adds a PickupLine cog containing the `pickupline` command, which picks a random pickup line from a JSON file, with an appropriate image per line.
Placeholder image for those without one is a line of trucks with cheese blocks (a cheesy pickup line)
> Pickup Lines

- bot/seasons/valentines/savethedate.py
---
name: Save the Date fix
about: Move the loading of the static JSON in the Save the Date cog
issue: #147 
---
Solves this issue by moving the loading of the JSON file into the module namespace, so that it is not loaded every time the command is called
> Save the Date - Static Resource Load

- bot/seasons/easter/__init__.py
As the Easter season is starting on the First of April, to contain April Fools, (April 1st) and Earth Day ( April 20th) and of course Easter Celebration. 
Closes #128
> setting up easter directory for the easter season

- bot/__init__.py
Adds the TRACE logging level that's present in the regular bot. The snake cog brought along the pagination code, which has trace logging. 
The level will be enabled for both stdout and file when SEASONALBOT_DEBUG environment variable is True. If it's false, the defaults of INFO for stdout and DEBUG for file apply.
Closes #149
> Add TRACE logging level (Fixes #149)

- .dockerignore
- azure-pipelines.yml
- docker/Dockerfile
- docker/docker-compose.yml
The aim is to reduce the time of jobs by tinkering with options and removing unnecessary steps and dependencies.
> CI & Deployment Cleanup

- bot/seasons/easter/__init__.py
The easter icon has been added to branding. This PR adds the `icon` attribute for the Easter season class, and sets the season embed colour to pink.
> Add Easter icon url and embed colour.

- bot/seasons/evergreen/lemonstats.py
> Add lemon counter

- bot/resources/easter/egghead_questions.json
- bot/seasons/easter/egghead_quiz.py
---
name: Egghead Quiz
about: A command that asks questions of which responders can react with emojis
Closes #169 
---
This adds the EggheadQuiz cog containing the `eggquiz` command, which asks a question in the chat and sends the answer and vote spread 30 seconds later.
This image shows what the command looks like
> Egghead Quiz

- bot/seasons/easter/egg_hunt/cog.py
- bot/seasons/easter/egg_hunt/constants.py
This addresses the following issues:  
- Uneven distribution of team assignments, even though blurple team rules.
- Super eggs failing to drop and then being forgotten in the sands of time
- Rank making everyone a winner. Real life is harsher than that.
- Leaderboard did a big fat nothing before the event because there was no scores and `max()` didn't like an empty list.
> Egg Hunt Fixes

- Pipfile
- Pipfile.lock
- bot/seasons/christmas/adventofcode.py
- bot/seasons/easter/avatar_easterifier.py
- bot/seasons/evergreen/snakes/snakes_cog.py
- bot/seasons/evergreen/snakes/utils.py
- bot/seasons/halloween/spookyavatar.py
- bot/seasons/season.py
- bot/seasons/valentines/be_my_valentine.py
> Change d.py Dependency from GH to PyPI

- bot/seasons/pride/pride_avatar.py
A simple addition to #209 that fixes #222 by adding a command listing the possible options for flags
> Pride Avatar Flags

- bot/__init__.py
- bot/resources/pride/anthems.json
- bot/seasons/easter/april_fools_vids.py
- bot/seasons/easter/avatar_easterifier.py
- bot/seasons/easter/conversationstarters.py
- bot/seasons/easter/egg_decorating.py
- bot/seasons/easter/egg_hunt/cog.py
- bot/seasons/easter/egghead_quiz.py
- bot/seasons/easter/traditions.py
- bot/seasons/evergreen/magic_8ball.py
- bot/seasons/evergreen/snakes/utils.py
- bot/seasons/halloween/8ball.py
- bot/seasons/halloween/hacktoberstats.py
- bot/seasons/halloween/halloween_facts.py
- bot/seasons/halloween/halloweenify.py
- bot/seasons/halloween/spookyrating.py
- bot/seasons/halloween/spookysound.py
- bot/seasons/pride/pride_anthem.py
- bot/seasons/pride/pride_avatar.py
- bot/seasons/season.py
- bot/seasons/valentines/be_my_valentine.py
- bot/seasons/valentines/lovecalculator.py
- bot/seasons/valentines/myvalenstate.py
- bot/seasons/valentines/pickuplines.py
- bot/seasons/valentines/savethedate.py
- bot/seasons/valentines/valentine_zodiac.py
- bot/seasons/valentines/whoisvalentine.py
Will allow users to send .prideanthem with an optional genre supplied to receive a random anthem. If there are no videos for the supplied genre, it will let the user know.
> Implemented .prideanthem command

- bot/seasons/christmas/__init__.py
- bot/seasons/easter/__init__.py
- bot/seasons/evergreen/__init__.py
- bot/seasons/halloween/__init__.py
- bot/seasons/pride/__init__.py
- bot/seasons/season.py
- bot/seasons/valentines/__init__.py
---
name: Evergreen Animated Server Icon Cycling
about: Changes to the season logic to allow for cycling of icons daily
Closes #229 
---
This adds the four animated versions of the default logo to the evergreen icons and alters the season logic to allow for seasons to contain a list of items that can be cycled through daily
> Cycle Evergreen Animated Server Icons

- bot/seasons/evergreen/issues.py
Closes #210 
Command to call issues:
`.issue 210` - Calls issue 210 from Python Discord Seasonal Bot
`.issue 210 meta` Calls issue 210 from Python Discord Meta
`.issue 210 rohanbot rohanradia` Calls issue 210 from RohanRadia's Rohanbot repository
`.issue <issue number> [repository name] [user]`
Repository Name default is `seasonalbot`
User default is `python-discord`
> Created the .issue command

- bot/resources/easter/bunny_names.json
- bot/seasons/easter/bunny_name_generator.py
This cog contains two commands: '.bunnyname' and '.bunnifyme'.
**.bunnyname**
Simply picks a random bunny name from a JSON file of pre-generated names and returns the name as plain text.
**.bunnifyme**
This one is a bit more complex. The command uses regular expressions to match the user's display name against several different patterns.
First the display name is searched for separators and whitespace. If it contains either of these, one of the words in the name will be replaced with a bunny-related word. E.g. "Operative Loren" could become "Operative Cotton" or "Cotton Loren".
If the display name contains no spaces or separators, it will search for vowels in the name. If the display name contains a vowel and the letter y, it will replace the part between those two characters with …
> Bunny Name Generator

- bot/resources/easter/easter_riddle.json
- bot/seasons/easter/easter_riddle.py
Closes #177 
Adds a new command to the seasonalbot, called by `.riddlemethis` or `.riddleme`, that prints a riddle to the Discord server the bot is in. The questions are chosen from a pool of 10. After 10 and 20 seconds from the initial command, the bot will print a hint to help the users with the riddle. After 30 seconds, the bot will print the results.
- If nobody wins, the bot will say so.
- If one person wins, the bot will say so and ping them.
- If multiple people win, the bot will ping them all.
The riddles are in the form of a text sentence.
> Implemented .riddlemethis for the Easter season

- .gitignore
- bot/resources/evergreen/speedrun_links.json
- bot/seasons/evergreen/speedrun.py
Created a speedrun cog that allows the command .speedrun which will grab a link from the supplied speedrun_links.json and send it to the discord channel.
> Add speedrun cog and resource

- bot/seasons/evergreen/minesweeper.py
added the minesweeper command,
it is played in dms, and a mirror of the board is updated in the channel the command was run in. 
it is 10 by 10, you can specify the chance of a cell being a bomb (defaults to .2) must be between 0 and 1.
> Minesweeper

- bot/seasons/evergreen/minesweeper.py
> fixed coordinate bug.

- bot/seasons/evergreen/minesweeper.py
if somebody uses 100% every cell will be a bomb and they can't win, this makes sure always that one cell is free. no matter how unlikely you are to hit it.
> [Minesweeper] making sure there is always a non-bomb cell.

- bot/seasons/evergreen/minesweeper.py
if you lose the bomb that triggered the losing is marked with an X and it only reveals the bombs
if you win, it does not reveal the bombs
> [minesweeper] changed board revealing at end of games.

- bot/seasons/evergreen/fun.py
- bot/utils/__init__.py
This PR implements fun commands to modify given text.
A utility function was implemented to replace multiple words in a string.
> Modify text :-)

- Pipfile.lock
- bot/constants.py
- bot/resources/halloween/monster.json
- bot/seasons/halloween/monster.py
- bot/seasons/halloween/monsterbio.py
---
name: Monsterbio
about: Adding the monsterbio command.
issue: Issue number #30
---
Implements a command that gives a bio for your monster self.
Please ensure your PR fulfills the following criteria:
Provide any additional information or clarifications here.
> Adds the monsterbio command

- bot/constants.py
- bot/seasons/evergreen/bookmark.py
---
name: .bookmarks
about: helps to bookmark something useful along hint(s) to find in future.
issue: Issue #323 
---
Please ensure your PR fulfills the following criteria:
[✓] Have you joined the PythonDiscord Community?
[✓] Were your changes made in a Pipenv environment?
[✓] Does flake8 pass (pipenv run lint)
There is no check whether if the call is in the right channel or not , because seasonalbot do it itself.
example of the message
without any hints 
New one looks like this:-
Update 507863c
DM now look like this
> [Feature] `.bm` `.pin` bookmarks/personal-pins

- bot/constants.py
- bot/seasons/evergreen/movie.py
Closes #345 
Closes #306 
Added `.movie <genre> <amountofmovies(default 5)>` command, genres can be get with .movie command (run .movie command help). Used subcommands.
I added this due much peoples wanted it, they opened issue, and some of these issues got approved.
> .movie Command Adding

- bot/constants.py
- bot/seasons/evergreen/game.py
Closes #354
Closes #278 
I added `.games <genre> <amount (default 5)>` command + all it's subcommands:
- `.games top <amount, default 10>` - Get current top games
- `.games search <search string>` - Search games by title
- `.games genres` - Get all current available genres
- `.games companies <amount default 5>` - Get random game companies
I used IGDB API for this.
I added this due I lately added `.movies` command and current game recommendation command is pretty limited.
> Added .games command

- azure-pipelines.yml
#368
The name is needed to be able to retrieve its output variable, `pythonLocation`. It's used by the pre-commit cache and the pipenv mock steps. I forgot to include it in the original PR.
> Name the use Python version task

- Pipfile
- Pipfile.lock
- bot/__main__.py
- bot/constants.py
- bot/seasons/evergreen/error_handler.py
Finishes part of the organisation issue for Sentry setup: python-discord/organisation#209
Sentry SDK has been installed. A special handler for command errors has been setup.
SEASONALBOT_SENTRY_DSN is present within the seasonalbot environment already.
> Setup Sentry

- bot/seasons/evergreen/game.py
Closes #369 
I added matching function (thanks to @ikuyarihS for code).
Due currently when you type genre wrong, this only suggest genres, but this will auto use correct genre.
> Game genre matching fix

- bot/exts/evergreen/error_handler.py
- bot/exts/evergreen/minesweeper.py
- bot/exts/evergreen/space.py
- bot/utils/exceptions.py
Closes #388 
Closes #387 
Added a try-except block to Minesweeper and date check to APOD command.
> APOD and Minesweeper command fixes

- bot/constants.py
- bot/exts/evergreen/issues.py
Adds the dev contrib channel to channel constants and adds it to the issue command channel override
> Allow issue command in dev-contrib channel

- bot/exts/evergreen/snakes/snakes_cog.py
Changed Prefix in .snakes about from ! to .
https://github.com/python-discord/seasonalbot/issues/374
Closes #374
Changed prefix from ! to .
The prefix used to be ! but the commands were using a . prefix
> Fixed Prefix and Website

- bot/constants.py
- bot/exts/evergreen/fun.py
Closes #440.
- Emojis in `constants.py` were replaced with the new emojis, following the dice redesign
- `.roll` command was updated to use the new emoji names in `constants.py`
> Update .roll to use new dice emojis

- bot/exts/evergreen/reddit.py
Changed the ID's to use ID's of new emojis.
Old emojis were removed from the server and moved to emojis server.
> fix `reddit` command to use new emojis.

- bot/exts/evergreen/issues.py
Closes #398
By looping through the set of number(s) given by the user, this bot will acquire as many links as it can. All links acquired are appended to a list, which is eventually formatted and put into an embed. If any of the issue/PR numbers are incorrect, the bot will stop at the first one giving the error and let the user know what the response from GitHub was.
The loop will be broken out of at the first error, since it's possible a user could send a bunch of faulty requests by spamming large amounts of numbers. If the loop is broken out of at the first one, nothing will occur.
Support for issues and PRs at the same time:
Single issues or PRs still work:
Duplicates removed:
Issue/PR not found:
> Updated issue/PR command to acquire multiple links.

- bot/constants.py
- bot/exts/evergreen/issues.py
This PR changes a few things for the `.issue` command:
- Allows use in #dev-branding 
- Limits the maximum PRs/issues to 10 per command invocation
- Invokes the help command when no PRs/issues are given
- Makes requests to the GitHub API with authentication
Just some small improvements for this command!
> Small fixes for the .issue command

- Dockerfile
- Pipfile
- Pipfile.lock
"Closes #432 "
uninstalled old dpy and installed new d.py with voice as extra
> updated d.py to 1.4.1 and added voice as extra

- bot/exts/evergreen/trivia_quiz.py
"Closes #351 "
this is a simple fix in check func
> Trivia: only fuzzy match messages sent in game channel

- bot/exts/evergreen/issues.py
Description
`numbers` was turned into a set twice, so I removed the second conversion
> remove redundant set() in issues.py

- bot/exts/easter/easter_riddle.py
closes #498 
`self.winners` is now a set, and when updating, `add()` will be called, and `clear()` will be called when it needs to be cleared
before/after
> remove duplicate winners for .riddle

- bot/exts/evergreen/movie.py
- bot/exts/halloween/scarymovie.py
- bot/exts/valentines/movie_generator.py
> Comply with TMDB API ToS

- bot/exts/halloween/hacktober-issue-finder.py
- bot/exts/halloween/hacktoberstats.py
closes #474 
closes #491 
closes #504 
for hacktoberstats, prs with spam labels doesnt count as well
edit: and with updated rules, the logic must be updated
**New rules**:
1. PRs before Oct 3: must not have "invalid" or "spam" labels
2. PRs after Oct 3: must be in a repo with "hacktoberfest" logic (unless it has the "hacktoberfest-accepted" label)
> update hacktoberstats logic for updated rules

- bot/exts/evergreen/emoji_count.py
I have added Linepaginator and added check for animated emoji, so now if embed description limit exceeds bot automatically creates new embed and add pagination emojies to it
> [Bug] emoji command

- .github/workflows/lint-build-deploy.yaml
- deployment.yaml
Add a Kubernetes deployment stage to GitHub Actions. This uses the Azure set-context and k8s-deploy GitHub Actions.
> Add Kubernetes deployment job

- bot/constants.py
Adds a new general voice text channel to the constants, and renames the channels to match the new configuration. [Announcment with details](https://discord.com/channels/267624335836053506/748238795236704388/799648464061464577).
> Adds New Voice Chat Channel To Constants

- bot/exts/evergreen/battleship.py
"Closes #563 "
changed index to upper so it will not out of bound 
- [x ] If dependencies have been added or updated, run `pipenv lock`?
- [x ] **Lint your code** (`pipenv run lint`)?
- [ x] Set the PR to **allow edits from contributors**?
> issue #563 fixed changed to upper case

- bot/__main__.py
- bot/exts/christmas/advent_of_code/_cog.py
- bot/exts/evergreen/cheatsheet.py
- bot/exts/evergreen/conversationstarters.py
- bot/exts/halloween/hacktoberstats.py
- bot/utils/decorators.py
This PR removes the in_channel_override, with the more feature-rich whitelist_check. This allows for more granularity with the checks. Other improvements include allowing commands to ignore the global checks if need be.
The improvements will not materialize immediately in this PR, but it will help other currently open PRs in implementing features smartly.
The whitelist_check allows the checks to utilize categories, and roles, whereas previously category checks weren't possible, and role checks weren't available to the overrides.
> Upgrade override

- bot/constants.py
- bot/exts/evergreen/issues.py
Add staff category and staff voice to `constants.py` and added them to the list in the issues cog.
To make use of the already present code.
> Add issue cog to staff channels.

- bot/resources/evergreen/py_topics.yaml
- bot/resources/evergreen/starter.yaml
We haven't updated the topics in the `.topic` command for a while. 
Some of the topics included in the `#python-general` section including IDEs were problematic, so we moved them over to the `#editors-ides` channel.
Many more topics have been added for offtopic channels.
> Added more topics.

- bot/resources/evergreen/trivia_quiz.json
…rder again
Closes #592
I deleted the Question about the longest river and then changed all following IDs to match the order again
The answer to this question is not definitively "nile"
- [x ] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x ] If dependencies have been added or updated, run `pipenv lock`?
- [x ] **Lint your code** (`pipenv run lint`)?
- [x ] Set the PR to **allow edits from contributors**?
> Removed the Question about the Nile

- .github/workflows/build.yaml
- Split build stage into build & deploy
- Set environment for deploy stage
> Deployment changes

- bot/resources/easter/april_fools_vids.json
> Remove broken link from the April fool collection

- bot/resources/easter/april_fools_vids.json
Added 3 New Elements To The .Json
> Added 3 More Elements To The Json

- bot/resources/easter/april_fools_vids.json
#639 left the json file in a broken state, not letting the bot start.
> Add missing commas to april_fools_vids.json

- bot/resources/evergreen/starter.yaml
Removed the `Name one thing you like about a person to your right.` topic as it doesn't make sense in discord
Closes #664 
Removed the topic
Its not really answerable on discord.
> Remove topic that doesn't make sense in discord

- bot/resources/easter/easter_riddle.json
Deleted a riddle from the resource file
This riddle isn't the best, and one of the hints is inappropriate for our server.
> Remove inappropriate riddle

- .github/pull_request_template.md
This is a rewording of the comments in the PR template, to hopefully clarify intentions.
It also removes unneeded fields.
Closes #685.
Rewords portions of the PR template to clarify intentions through comments, and removing unneeded fields.
Make sure to view the raw file to see the comments.
This field is gone, shoo.
This field is gone as well.
This one too.
> Reword PR Template

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/sentry_release.yaml
- .github/workflows/status_embed.yaml
This stops different actions, from the same commit, running in parallel from canceling each other.
> Namespace each concurrency group

- bot/exts/evergreen/error_handler.py
> (hotfix): Add __init__ to error handler cog

- bot/resources/evergreen/trivia_quiz.json
This closes #747 
added "centisecond" to the json file.
> Added "centisecond" in  trivia_quiz.json

- README.md
closes #759 
Now our README.md will directly redirect to respective link of contribution instead of empty Contribution.md
> changed contribution link

- Dockerfile
The previous way would error out when building due to not being able to find a file on the overwritten
path. https://paste.pythondiscord.com/alixoqaxuc.py
This can be reproduced by doing a full rebuild of the container.
> Install Poetry globally in Docker

- bot/constants.py
- bot/exts/evergreen/issues.py
Github updated their icons, so we should update ours too.
Once merged, we should delete the old emoji form the emoji server to open up room
> Update Github emoji to new icons

- bot/constants.py
- bot/exts/halloween/hacktoberstats.py
Closes #780
The hacktoberfest channel has now been removed, so these overrides can also be removed.
The commands may still be useful in future, and can be used in lancebot's playground.
> Remove hacktoberfest channel overrides

- bot/exts/evergreen/avatar_modification/avatar_modify.py
Following a moderation decision, we have decided to not allow any commands that parrot arbitrary images back via the bot, or anything that members can run against other members with their permission.
> Remove user input images

- bot/exts/halloween/scarymovie.py
Closes #769 
I modified the code to use the proper API endpoint, and changed the HTTP parameters accordingly.
Also, I removed a reference to an environment variable, that was unnecessary. ( That parameter (TMDB_TOKEN) wasn't even present in the list on the [Wiki](https://pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/env-var-reference/)).
I have also added a new filter `"include_adult": "false"` , to make sure it won't return inappropriate results.
(That was my first ever pull request to an open-source project, I'd like to apologize for the possible mistakes I made, in advance)
> Fix .scarymovie command (Halloween)

- bot/constants.py
Adds IDs for the `.stackoverflow` command, replacing the placeholders that I forgot to replace.
> Added stackoverflow emoji IDs to constants.py

- bot/exts/evergreen/githubinfo.py
- bot/exts/evergreen/movie.py
- bot/exts/evergreen/stackoverflow.py
- bot/exts/evergreen/wikipedia.py
- bot/exts/evergreen/wolfram.py
- bot/exts/halloween/hacktoberstats.py
- bot/exts/valentines/movie_generator.py
Closes  #801
I applied the built in tools from aiohttp wherever I could to properly sanitize the inputs, in case of the GithubInfo Cog, because of the API architecture I had to use a different approach, but by switching to `quote_plus` I managed to fix the issue.
The cogs fixed:
- Movie
- Githubinfo
- Wikipedia
- Hacktoberstats (get_october_prs function in particular [link](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/halloween/hacktoberstats.py#L217-L228))
> Circumvent URL Injections in various Cogs

- bot/exts/evergreen/avatar_modification/_effects.py
- bot/exts/evergreen/avatar_modification/avatar_modify.py
Closes #715
Resized images to 1024x1024 before applying effects. Also made a small refactor
> Avatar effects fix

- .github/workflows/build.yaml
Update in accordance with python-discord/kubernetes#95
> Update manifest path

- bot/exts/events/advent_of_code/_helpers.py
This caused some cogs not to load.
> Post re-structure fixs

- bot/exts/core/extensions.py
since the restructure of lancebot, this code was incorrect, and is no longer blacklisting itself.
https://canary.discord.com/channels/267624335836053506/635950537262759947/889975185279709225
Fixed the path name.
> properly blacklist the extensions cog

- bot/exts/utilities/bookmark.py
Closes #819
Added some further information in the error message as to what is accepted as a target message to bookmark.
> Give the bookmark command a better error message

- bot/resources/utilities/py_topics.yaml
Closes #934 
I deleted the line from the yaml
> Remove the "what's your skill level topic"

- bot/exts/events/advent_of_code/views/dayandstarview.py
- \- (The relevant issue has already been closed)
The PR introduces a quick fix to the AoC day and star stats feature, since it was tested on a fully populated leaderboard.
> Add check to ensure the day-and-star data exists

- bot/constants.py
- bot/log.py
Approved by me.
Decoupled file logging from the environment variable, and moved it behind it's own variable.
See python-discord/bot#1966 for details behind this change.
> Disable File Logging By Default

- bot/utils/pagination.py
pick 3cd4c92b1e24c8cfdae8c5c68c19607c62cc01ed from python-discord/bot
remove additional unnecessary edit
https://discord.com/channels/267624335836053506/635950537262759947/911629641662480444
> Remove unnecessary edits during pagination

- bot/monkey_patches.py
This trivial change is actually to try and reproduce a bug we had with our GitHub actions.
> Change single quote to double quote.

- bot/resources/utilities/py_topics.yaml
- bot/resources/utilities/starter.yaml
Closes #986
Adds a bunch of new topics, although I am unsure about some of them, so this PR is here to fix that uncertainty. 
If you have any more suggestions at this time, please comment your ideas!
> Added even more conversation starter topics.

- bot/exts/events/trivianight/__init__.py
- bot/exts/events/trivianight/_game.py
- bot/exts/events/trivianight/_questions.py
- bot/exts/events/trivianight/_scoreboard.py
- bot/exts/events/trivianight/trivianight.py
Closes #903
This is for the trivia night event, and will be the implementation of it into sir lancebot.
There are a few main commands:
`.trivianight load (file)`
This will load the JSON file attached as the questions for the cog to handle for when the event starts.
`.trivianight start`
This will begin the event (this could possibly send an embed regarding the start of the event)
`.trivianight next`
This will head to the next question, displaying the question in a configured channel and letting users pick a choice. They can pick again if they wish to do so but after that, an ephemeral will be sent saying that they cannot pick again after the second time.
`.trivianight stop`
This will display the correct answer and award points accordingly
`.trivianight question #`
This will head to the …
> Trivia night event

- bot/resources/utilities/py_topics.yaml
Closes #1052 
Added topics for the `.topic` command for the recently created `#media-processing` channel
> Add topics for `#media-processing` channel

- bot/resources/fun/latex_template.txt
Closes #1057 
This PR includes the amsmath in the default LaTeX template using `\usepackage{amsmath}` so that people can use Amsmath commands in the .latex command.
> Add amsmath support

- bot/exts/utilities/realpython.py
Closes #1001
Displays [RealPython's Home Page](https://realpython.com/) when a user provides no query during a `.realpython` call.
Example:
> RealPython home page displayed on no user search.

- bot/exts/fun/battleship.py
- bot/exts/fun/connect_four.py
Raised by `!! Ritik Ranjan [*.*]#9230` in https://discord.com/channels/267624335836053506/267624335836053506/996389706289909812
Fixed incorrect type hints in two files.
> Fix incorrect type hints

- bot/constants.py
- bot/exts/fun/latex.py
https://discord.com/channels/267624335836053506/429409067623251969/1004482521779687534
Added the ds&a channel to the whitelisted channels for the latex command.
> Enable LaTeX command in ds&a channel

- bot/resources/fun/latex_template.txt
Closes #1086 
Updated the latex template to use more packages.
> add more packages to .latex

- bot/exts/core/help.py
- bot/exts/utilities/bookmark.py
Closes #918
This simplifies the bookmark implementation, and adds the ability to delete bookmarks in DMs.
To reduce complexity, the delete bookmark functionality actually allows users to delete any sir-lancebot message within their own DMs, and is labeled as such.
> Bookmark enhancements

- bot/exts/core/error_handler.py
- bot/utils/commands.py
Closes #1090.
Removed the call to `self.on_command_error`, so that errors from command suggestions are ignored. Also fixed an incorrect typehint that was added in #1064.
> Fix command suggestions.

- bot/resources/utilities/ryanzec_colours.json
Closes #1123 
Added an entry for `blurple`.
> Added `blurple` color

- bot/exts/utilities/wolfram.py
Closes #1109 
Added catching of all non-200 HTTP codes that didn't get caught before.
> Catch more status codes in Wolfram commands

- bot/exts/holidays/halloween/spookyreact.py
Closes #1142 
This change adjusts the regex pattern used in detecting `spooky` to include fun variants such as `spoopy` and `spookier`. The `k` is replaceable with a `p`, the `y` can be interchanged with `i` allowing `ier` and `iest` endings. (`yer` and `yest` are also valid). The number of `o`s remains at two (2) or more.
> Enhance spooky react to be more spoopy.

- bot/exts/fun/latex.py
Skipping issue, approved by me.
This PR makes the latex URL configurable via an environment variable, in an on-going dev-ops experiment. We may host the API renderer internally.
> Make The Latex API URL Configurable

- bot/exts/utilities/challenges.py
Closes #1168 
Updated the CSS class that was used for the soup to find new kata items.
> Update CSS class in soup target

- .pre-commit-config.yaml
Bumps isort to its latest version
> bump isort to 5.12.0 in precommit config

- bot/constants.py
https://github.com/python-discord/site/pull/882
@wookie184
> Add default unicode emoji for trashcan

- .github/dependabot.yml
- .github/workflows/build-deploy.yaml
- .github/workflows/lint.yaml
- .github/workflows/main.yaml
- .github/workflows/sentry_release.yaml
- .github/workflows/status_embed.yaml
- Dockerfile
- poetry.lock
- pyproject.toml
Commit descriptions say it all.
> Python 3.11

- Dockerfile
> Update base image to new repo org

- bot/utils/checks.py
Solves SIR-LANCEBOT-9W
Closes #1267
> Use the new code jam category name variable

- bot/exts/utilities/reddit.py
Otherwise this will error every morning while r/python isn't accessible
> Disable the r/python auto poster

- bot/exts/utilities/colour.py
- bot/exts/utilities/epoch.py
- bot/utils/halloween/spookifications.py
Fixes #1309 
This PR is no code change. It fixes incorrect type annotations.
> Fix type hint 

- bot/exts/utilities/reddit.py
> Re-enable the reddit autoposter

- bot/exts/utilities/rfc.py
#1342 
Closes #1342 
Added a `.rfc` utility command by using the JSON interface for RFCs at `https://datatracker.ietf.org/doc/rfc{id}/doc.json`, where `{id}` is a placeholder for the RFC ID.
> Add a `.rfc` utility command

- bot/exts/fun/quack.py
> Add ducky as an alias to quack command

- .github/workflows/build-deploy.yaml
> Update deployment CI to pull manifest from infra repo

- bot/__init__.py
- bot/constants.py
- bot/log.py
> Remove the need for calling dotenv manually by using pydantic

- bot/resources/utilities/py_topics.yaml
> Fix capitalisation of PyPI

- bot/exts/holidays/easter/easter_riddle.py
Closes #502
- Rewrote the riddle command to use discord's [wait for function](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=wait_for#discord.ext.commands.Bot.wait_for).
- Game ends when someone enters the correct answer.
> Changed riddle behaviour to match that of trivia

- bot/exts/holidays/holidayreact.py
Add the thrill of never knowing which heart might be used during Valentines holiday event reactions.
Closes #1447
> Add additional heart emoticon options for react

- bot/exts/core/help.py
- bot/utils/pagination.py
The `LinePaginator` has been migrated to `pydis_core`
The changes here are simply to reuse the paginator from the core lib.
> Use paginator from botcore

- bot/resources/fun/trivia_quiz.json
Closes #1501.
I decided to just rephrase the question, but I can also scrap it. I just didn't feel like renumbering a bajillion IDs.
> Trivia quiz: Fix question about surrogate codepoints

- .github/workflows/status_embed.yaml
Info on changes is in commits.
If this is deemed correct then I'll apply these changes to our other repos too.
> Improve embed status action

- bot/constants.py
- bot/exts/core/extensions.py
- bot/exts/fun/battleship.py
- bot/exts/fun/snakes/_utils.py
Closes #527
This removes some constants that were burried over the years, and reuses some constants that have been duplicated
> Cleanup constants

- bot/exts/fun/uwu.py
https://discordapp.com/channels/267624335836053506/635950537262759947/1284217021634187341
This is a small change, the cleaned content was not used in the uwu command.
> Use the cleaned in content in the uwu command
