python-discord/sir-lancebot

bot/cogs/hacktoberstats.py
Minor adjustment to the regex used to parse the repository name from the API's return URL so we're properly handling repositories like `discord.py`
=> Fix hacktoberstats to properly parse valid repository names with _ and .

bot/cogs/gif.py
Addresses issue #8, adding random spooky gif feature that takes use of the GIPHY API.
To take use of this cog, create a env. variable named GIPHY_TOKEN and use the token you get from https://developers.giphy.com, they have a very simple process of creating an app, just create an account and you should be able to make your app and get the API key.
=> Add random spooky gif feature.

Pipfile, Pipfile.lock, bot/constants.py, bot/seasons/christmas/adventofcode.py
This adds a few features regarding countdowns and notifications.
- Role subscriptions (I've already added the role in Discord)
- Role notifications
- Countdown command
- Countdown status
I've added a couple config things but they default to things already in the server so no environment changes are required.
=> AoC countdown

bot/resources/advent_of_code/about.json, bot/seasons/christmas/adventofcode.py
Minor tweak to the private leaderboard embed to display the membership count for the board
=> Add private board membership total to embed

README.md
Hey there, I noticed that the links in the further reading section currently do not work correctly.
I've gone ahead and fixed them while slightly rewording the sentence to make it sound more natural. Please let me know if I should revert the second change!
=> Fix markdown for further reading links

bot/seasons/christmas/adventofcode.py
Instead of toggling notification subscription status with one single `notifications` command, I have split it up and renamed them `subscribe` and `unsubscribe`, while keeping the old name and aliases as well as `sub` as alias for `subscribe`, and `unsub` for `unsubscribe`.
Please review carefully, I didn't test this in a live bot yet.
=> Split .notifications toggle command into .subscribe and .unsubscribe

bot/seasons/christmas/adventofcode.py
Adds an `.aoc stats` command to display the current completion statistics, by day
Also makes a minor fix to the leaderboard parsing regex to account for twitter handles, which start with a leading `@`.
=> Private Leaderboard Daily Completion Statistics

bot/bot.py, bot/constants.py, bot/seasons/season.py
Resolves #83 
A notification is sent to devlog on the new loading of a season. This means it will effectively send a notification on:
- Season changes to a special season
- Season changes to evergreen
- Bot starts/restarts and loads the current season
These notifications will be sent regardless of debug mode setting.
Notification posted to devlog looks like:
Additionally resolves a bug with the `load_seasons` method where on checking for different seasons at midnight, it would always think it's a new one, resulting in the devlog notification being re-sent every midnight.
=> Send devlog notification on season load.

bot/constants.py, bot/seasons/valentines/__init__.py
Implements a new valentines day season for the SeasonalBot.
~~Blocks on a PR being opened for python-discord/branding#1 to add an icon under `/logos/logo_seasonal/valentines/loved_up.png`.~~ python-discord/branding#4 has been merged
=> Add valentines season

bot/resources/valentines/love_matches.json, bot/seasons/valentines/lovecalculator.py
Recently a test of the .love command revealed an unintentional reaction
when 100% are reached. In previous versions this command had used a
gigantic conditional block, checking for the current percentage given by
the love_meter formula. When reaching 0 (meaning that the UserID's
evenly divided with 100) it would automatically convert that 0 to 100. A
big mistake from my side back then.
This has been fixed with these changes. By quickly modifying the formula
to use a mod 101 instead of a mod 100, we get an accurate percentage,
ranging from 0-100% instead of 0-99%. love_matches.json has also been
fixed to address these changes, meaning that the lowest entry now
actually is 0 and the highest 100.
TL;DR:
-> Edited love_meter formula to calculate mod 101 instead of mod 100
-> Edited lowest and …
=> Fix LoveCalculator 0% bug

bot/constants.py, bot/seasons/evergreen/fun.py
Add direct reference to terning emoji so they resolve properly when the `.roll` command is invoked.
=> Add Terning Emoji to Constants, Update Fun Cog

bot/constants.py, bot/resources/advent_of_code/about.json, bot/seasons/christmas/adventofcode.py
Refactor `.aoc join` to DM the user with the code.
Also updates the `.aoc about` to direct the user to get the current leaderboard code from the `.aoc join` command.
=> AoC Join Code Refactor

bot/resources/valentines/valenstates.json, bot/seasons/valentines/myvalenstate.py
Closes #108
This pull request adds a beta version of the command myvalenstate.
This command sends an embed containing a users valenstate to the channel
it has been called in. The process used here is to first put the username
into a spaceless, lower case form and than compare it to the countries
listed under valenstates.json, put into the same form, using an implementation
of the Levenshtein algorithm.
This beta version already implements everything needed for the command to
work properly. The follwing things are missing, not meant for the future
full implementation or are subject to change if needed:
- Short comments (25 missing)
- name parameter in myvalenstate (not meant for staying/Debug)
- Object names in valenstates.json (subject to change) (1)
- Docstring for levenshtein (subject …
=> Add .myvalenstate

bot/seasons/evergreen/__init__.py, bot/seasons/season.py
Closes #134 
Prevents SeasonalBot from applying the evergreen server icon during off-season periods. Server icon
will change accordingly during seasonal events.
=> Prevent SeasonalBot from changing server icon during off-season periods

bot/seasons/season.py
Announcements were setup previously to not send anything if no seasonal commands were found. Since we want to announce regardless to entice people to contribute, I've adjusted the logic to always announce, but only add the commands info if there were any found.
There was also a formatting issue with newlines and wrapping that was a result of using the docstring which we explicitly make a newline for when it gets close to linting max length. The new formatting process takes a docstring, splits by paragraphs, and then replaces any newlines with a single space, letting single paragraph blocks wrap correctly in the announcement embed. Example:
**Docstring**
```py
"""
Easter is a beautiful time of the year often celebrated after the first Full Moon of the new spring season.
This time is quite …
```
=> Always announce if docstring, better formatting.

bot/seasons/easter/__init__.py
This fleshes out the announcement to a proper one that's in line with our typical announcement style and info for these seasonal events.
It adds a mention about the server icon changing so less people ask why it's changed, a thanks to the person who chose the design colours, cleans the embed greeting to be less awkward and finally encourages people to actually join in the event itself by contributing or implementing ideas and popping into the seasonalbot chat channel to discuss the event.
=> Improve easter announcement.

Pipfile, Pipfile.lock, bot/seasons/christmas/adventofcode.py, bot/seasons/easter/__init__.py, bot/seasons/evergreen/error_handler.py, bot/seasons/evergreen/fun.py, bot/seasons/evergreen/magic_8ball.py, bot/seasons/evergreen/uptime.py, bot/seasons/halloween/candy_collection.py, bot/seasons/halloween/hacktoberstats.py, bot/seasons/halloween/halloween_facts.py, bot/seasons/halloween/halloweenify.py, bot/seasons/halloween/scarymovie.py, bot/seasons/halloween/spookyavatar.py, bot/seasons/halloween/spookygif.py, bot/seasons/halloween/spookyreact.py, bot/seasons/halloween/spookysound.py, bot/seasons/halloween/timeleft.py, bot/seasons/season.py, bot/seasons/valentines/be_my_valentine.py, bot/seasons/valentines/movie_generator.py, bot/seasons/valentines/myvalenstate.py, bot/seasons/valentines/pickuplines.py, bot/seasons/valentines/savethedate.py, bot/seasons/valentines/valentine_zodiac.py, bot/seasons/valentines/whoisvalentine.py
- Adds `commands.Cog` inheritance to cogs that are missing it.
- Update d.py version pin & relock
- Codebase is unaffected by any of the current breaking changes that followed the Cog change
- Re-add the Cog inheritance that I accidentally removed when resolving the flake8 merge conflicts and didn't notice until it got merged
- Bump Easter season back one day to accommodate April Fools
=> Cog inheritance hotfix

bot/constants.py, bot/seasons/christmas/adventofcode.py, bot/seasons/halloween/candy_collection.py, bot/seasons/halloween/halloween_facts.py, bot/seasons/valentines/be_my_valentine.py
---
name: Constant Clearing
about: Combining all the seasonal bot chat constants to one chat
Closes #192 
---
This PR removes any season-specific channel IDs and combines them into one `seasonalbot_chat` constant in `Channels`. 
This also changes any cogs which previously used the aforementioned channel IDs
=> Constants - Spring Cleaning

bot/seasons/evergreen/snakes/utils.py
The Snakes and Ladders game in the snake cog was broken because the BytesIO stream of the generated board image was handled incorrectly. This lead to the `ValueError: embedded null byte` exception we've seen before on another other older feature. (My guess is that a breaking change somewhere broke these relatively old pieces of code that did work before.)
I fixed it by replacing the lines handling the BytesIO stream with an existing utility function that does precisely what's needed and was already defined just above the lines containing the bug.
=> Fixing the Snakes and Ladders game

bot/__main__.py, bot/bot.py, bot/constants.py, bot/decorators.py, bot/seasons/christmas/adventofcode.py, bot/seasons/easter/egg_hunt/cog.py, bot/seasons/easter/egg_hunt/constants.py, bot/seasons/evergreen/error_handler.py, bot/seasons/evergreen/issues.py, bot/seasons/season.py
This PR restricts SeasonalBot commands to these channels:
* bot-commands, seasonalbot_commands
* ot0, ot1 and ot2 channels
* dev-test
To do so, functionality was added `in_channel` to allow a list of roles that bypass the check. The predicate function and the actual `discord.ext.commands.check` was separated so the predicate can be added as a global check to the bot.
The `in_channel` check can be overriden for certain commands using a decorator. Commands that currently have the override are `!issue` and `!adventofcode`.
To avoid circular imports, the bot instance definition was moved to the same file as the `SeasonalBot` class, `bot.py`. 
Constants brought over from the Python bot:
* MODERATION_ROLES, STAFF_ROLES
* NEGATIVE_REPLIES, POSITIVE_REPLIES
=> Limit SeasonalBot commands to whitelisted channels

bot/resources/evergreen/game_recs/chrono_trigger.json, bot/resources/evergreen/game_recs/digimon_world.json, bot/resources/evergreen/game_recs/doom_2.json, bot/resources/evergreen/game_recs/skyrim.json, bot/seasons/evergreen/recommend_game.py
Created the RecommendGame cog with `.recommend_game` command as well as a new directory, `bot/resources/evergreen/game_recs`, for game recommendation files in .json to be stored and used by the cog. I added 4 different game recommendations to start with.
Current Embed formatting is as such:
=> Add RecommendGame cog and resources

bot/pagination.py, bot/seasons/evergreen/snakes/snakes_cog.py, bot/seasons/evergreen/snakes/utils.py, bot/seasons/halloween/monstersurvey.py, bot/seasons/valentines/be_my_valentine.py, bot/utils/__init__.py
This PR replaces paramater and return value docstring documentation with an extended summary or description.
=> Remove parameter and return value documentation from docstring

.pre-commit-config.yaml, CONTRIBUTING.md, Pipfile, Pipfile.lock
* Update contrib doc to emphasize allowing edits from maintainers to a user's fork (see: https://github.com/python-discord/organisation/issues/114)
* Add the pipenv linting script to the pre-commit rather than having to mirror settings (see: https://github.com/python-discord/organisation/issues/96)
* Add dependency pinning & relock
=> Update contrib doc for allowing edits from maintainers

bot/seasons/christmas/adventofcode.py, bot/seasons/easter/avatar_easterifier.py, bot/seasons/easter/bunny_name_generator.py, bot/seasons/easter/easter_riddle.py, bot/seasons/easter/egghead_quiz.py, bot/seasons/easter/traditions.py, bot/seasons/evergreen/8bitify.py, bot/seasons/evergreen/minesweeper.py, bot/seasons/evergreen/showprojects.py, bot/seasons/evergreen/snakes/utils.py, bot/seasons/evergreen/speedrun.py, bot/seasons/halloween/candy_collection.py, bot/seasons/halloween/hacktoberstats.py, bot/seasons/halloween/monstersurvey.py, bot/seasons/halloween/spookyrating.py, bot/utils/__init__.py, tox.ini
This PR addresses some issues in 2 cogs:
**Hacktoberfest**
Some minor cleanup to get the cog ready for the upcoming event:
* Fix command typo in account linking helper message
* Remove hardcoded values for event year & number of PRs before one gets a shirt, adjust related functionality
* Some type hinting kaizen in advance of #248
**Snakes**
The Snakes and Ladders command has been updated:
* The game can now be played solo
* Add missing `await` to the reaction timeout while waiting for the game to start, preventing the game from being cancelled after the timeout is reached & freeing the channel for another game
* Update cancellation logic as follows (per #253):
* Game has timed out
* There are no players left in the game
* Non-player Moderation staff can cancel the game at any time
* …
=> Hacktoberfest update & SaL Fix

bot/seasons/evergreen/fun.py
This PR adds functionality to also modify the title, description, footer and any fields in an embed, as well as the message contents itself when passed to a text-modify command like `.uwu` or `.rcase`.
Although messages may potentially have multiple embeds, currently only the first embed is selected, converted and sent because:
- Only webhooks can have multiple embeds in the same message
- Bots cannot send more than one embed per message
Fixes kaizen'ed together are:
- Add `some -> sum` conversion for the `.uwu` command
- Improved help documentation for the text-modify commands to specify that a discord Message ID or link is also accepted
- Do not preserve the block quote characters `>>>` for chained conversions. Previously, calling the command again on a quoted text results in duplicated …
=> Modify text of embeds for text-modify commands

Pipfile, Pipfile.lock, bot/seasons/easter/avatar_easterifier.py, bot/seasons/evergreen/fun.py, bot/seasons/season.py, bot/seasons/valentines/lovecalculator.py
flake8-annotations v1.1 was recently released, which includes a fix for incorrect parsing of nested functions.
This PR updates the dependency pinning & fixes the annotations that were missed previously.
=> Update flake8-annotation pin & relint

bot/seasons/halloween/__init__.py, bot/seasons/season.py
The Halloween season was currently configured to run with spooky icons and to announce a terrible, contentless announcement.
This has been disabled and the neon hacktoberfest icon has been placed in its stead.
This has to be merged _today_, so please make post-haste, good Sirs and Ladies.
=> Disable halloween announcement and add hacktober icon.

bot/constants.py, bot/decorators.py, bot/seasons/christmas/adventofcode.py, bot/seasons/evergreen/issues.py, bot/seasons/halloween/hacktoberstats.py
This PR extends the date ranges of the search query to cover the beginning of October in the first timezone and the end in the last timezone;
Adds the 2019 Hacktoberfest channel to the white-list for bot commands.
Closes #282 #283
=> Hacktober date range and channel whitelist fixes

bot/decorators.py, bot/seasons/halloween/hacktoberstats.py
In the rewritten in_channel_check, if the command override was used, role bypass wouldn't take effect because the function would exit before it. This PR puts the bypass check above the override check to make sure the roles will bypass it.
=> Put role bypass check above channel override check

bot/seasons/evergreen/__init__.py
In https://github.com/python-discord/branding/commit/6b606dd0b3d96d9d59b75686a528261a292e55c1, we have added two new animated logos to the branding repo, however they were not added to the icon constant in seasonalbot, which prevents them from being picked.
This PR adds the two new logos to the constant.
Update: In 7ad0b0a1d6b1d4adbe8dfb9ef6afb9804262aca2, the logos are adjusted to 512 size to (hopefully) prevent a bug where the image doesn't properly display client-side.
=> Add two new icons to icon constant

bot/seasons/evergreen/__init__.py
---
name: Add the new blinky server guild icon to the shuffle
about: A new server icon was created at: https://github.com/python-discord/branding/pull/35 and needs to be added to the shuffle.
issue: None.
---
Adds one more icon to the shuffle.
Please ensure your PR fulfills the following criteria:
=> Add the new blinky server guild icon

bot/constants.py
---
name: AoC year fix
issue: Issue #310 
---
* Previous the year was a magic number. This PR adds datetime.utcnow() to fix this.
* Support for an `AOC_YEAR` env var is also added for local debugging
* Leaderboard ID updated
Closes: #310
=> Advent of Code year binds to datetime instead of a magic number

bot/seasons/season.py
As we start to incorporate special events into our seasons, it's often desired to make announcements manually with details of the event rather than doubling announcements, particularly if the event begins on the first day of the season.
Currently, announcement handling is disabled for a hardcoded list of seasons, this PR instead adds a boolean flag to the `SeasonBase` that allows for per-season configuration of whether or not to send an announcement at the beginning of the season. This is currently defaulted to `False`, disabling all announcements, and per-season `True` values can be added in a later PR after a discussion on which seasons we'd like to announce automatically.
=> Default seasons to not send announcements

bot/seasons/christmas/__init__.py
Updates the path to the server icon for the 2019 festive season.
Requires https://github.com/python-discord/branding/pull/38 to be merged first.
=> Update icon path for 2019 festive season

bot/seasons/christmas/adventofcode.py
Fix the `brief` argument for `.aoc join` to make its behaviour more obvious.
=> Reword the aoc join command brief description to make behaviour more obvious.

bot/seasons/christmas/adventofcode.py
Right now, two instances of the aoc related asyncio tasks are running at the same time, this PR make sure only one is running.
=> Cancel season related tasks on cog unload

bot/constants.py, bot/seasons/christmas/adventofcode.py
As explained in #322, when a user runs `.aoc join` and their DMs aren't disabled, there is a lack of feedback from the bot. Adding a simple reaction to their message will amend this - it won't look like the bot ignored the request, and we will know that everything went smoothly for the user.
In 40ff465 we add an emoji constant 📨.
In 4af0413 we add an `else` clause to the try-except and add the reaction if everything goes smoothly.
Closes #322.
=> Add envelope reaction on successful AoC join DM dispatch

bot/resources/advent_of_code/about.json, bot/seasons/christmas/__init__.py, bot/seasons/christmas/adventofcode.py
The current time delta until the next AOC event assumes that the next event is next year's. While this is was a safe assumption when written, since the command would not be available until the season is loaded on December 1st, it provides an incorrect answer if the season is loaded prior: 
The logic has been adjusted to return the closest December 1st that is not in the past. The feedback string has also been adjusted to give hours remaining if we're less than a day away from the event starting:
(The second invocation uses November 1st for testing purposes)
The information embed has also been updated to remove the hardcoded year from the link to the global leaderboard. The hardcoded year is unnecessary & the site should redirect to the current event so we don't need to update this value …
=> Fix AOC countdown logic

bot/seasons/halloween/hacktoberstats.py
**Closes #304**
Draft Pull Requests still count as valid in the current `.hackstats` command but do not for the official DigitalOcean event.
This is mitigated by checking for the `draft` field and ignoring PRs where it is `True`.
=> Ignore Draft PRs in .hackstats

bot/constants.py, bot/seasons/christmas/adventofcode.py, bot/utils/__init__.py
Currently, the message Merrybot sends to announce that a puzzle has become available does not ping the members that have subscribed to these messages. The reason is that we have introduced a more stringent role mentionability policy to prevent abuse; this means that the `Advent of Code`-role is no longer pingable by default. This PR makes sure that the bot unlocks the role before sending such an announcement.
In addition, I've have slightly tweaked the sleep time, since the bot has a history of sending the message slightly too early, and fixed some small mistakes in the code. The puzzle message will now also be sent to the `#advent-of-code` channel.
In order to safely unlock the role, I've written an async context manager that takes care of unlocking and relocking the role and added it to …
=> Make the daily Advent of Code subscription service actually ping subscribers

bot/seasons/evergreen/error_handler.py
Closes #307 
- CRLF (Windows) line separators changed to LF (Unix)
- Create `error_embed` classmethod to build error embeds consistently
- Make all handled error types use `error_embed` method for any user responses
- Remove error-specific debug log messages and have a generic debug log at the top
- Log unhandled errors with `log.exception` instead of using `logging.warning`
- Have full traceback shown in stderr with `log.exception` by passing `exc_info`
- Use `math.ceil` on `retry_after` instead of within f-string to be cleaner
- Have the command signature sent to show how to use it when users invoke it incorrectly (`UserInputError`, `BadArgument`)
- Make channel check errors delete themselves after 7.5 seconds (as per suggestion from lemon)
Our projects use LF line separators and it …
=> Use error_embed for errors, tidy code, show cmd signature for user errors.

bot/seasons/evergreen/bookmark.py
---
name: Fix to prevent leaking of staff channel leaks.
issue: #339 
---
This PR adds a permissions check to prevent users from bookmarking a message from a channel they do not have read permissions for. Because the bot has permissions in these channels, it can leak message contents to the user via DM
Closes: #339 
Please ensure your PR fulfills the following criteria:
=> Added  permission check for staff channels message leak.

bot/constants.py, bot/seasons/season.py
Adds a configurable constant, which determines the amount of days to wait between cycling icons within a single season. See my conversation with lemon: https://github.com/python-discord/organisation/issues/191#issuecomment-590086579 and below.
@lemonsaurus I liked your suggestion with using `itertools.cycle`, but I decided to just keep internal state as an int. The reason here is that we can easily reset it back to 0 if we switch seasons.
I tried to keep the implementation as simple as possible. It can be tested by manually setting `sleep_time` to a few seconds. Running this loop with a `sleep_time` forced to 3 seconds and logging set to `DEBUG` produces the following output.
```
02/23/20 20:03:41 - bot.seasons.season DEBUG: Days since last icon change: 1
02/23/20 20:03:41 - …
```
=> Icon switch frequency

bot/constants.py, bot/seasons/easter/__init__.py, bot/seasons/easter/egg_facts.py, bot/seasons/evergreen/issues.py, bot/seasons/halloween/candy_collection.py, bot/seasons/halloween/halloween_facts.py, bot/seasons/pride/__init__.py, bot/seasons/pride/pride_facts.py, bot/seasons/valentines/be_my_valentine.py, docker-compose.yml
Redirect any output to seasonalbot commands, where relevant.
=> Strip references to seasonalbot chat

Dockerfile, Pipfile, Pipfile.lock, azure-pipelines.yml
This PR essentially replicates the efforts of https://github.com/python-discord/bot/pull/783.
Bumps Python to 3.8 in Pipfile & lock, Azure and Docker.
Bumps the Ubuntu image in CI to 18.04.
So far it appears that Seasonalbot is fully compatible with 3.8 (tested on 3.8.2) as is, without any required adjustments. I will test some more tomorrow before taking this out of draft status.
Closes #372
=> Bump Python version to 3.8

.gitignore
Closes #379
Make git ignore the directory that the persistence module writes to. Prevents accidentally adding it to version control.
=> Add `data` persistence directory to .gitignore

bot/bot.py
Closes #390 
The issue gives a fairly though explanation. Implementation is simple, as we already have a method for dispatching embeds to the `#dev-log` channel. In 6af47f8, we first ensure that the cache is ready before grabbing the devlog channel instance.
The author field is always populated with `SeasonalBot` - the seasonal nickname isn't used.
=> Send greeting message on bot start-up

bot/bot.py
Sometimes, `wait_until_ready()` passes even if the cache isn't ready yet.
In such a case, we attempt to fetch the channel via an API call.
=> Try to fetch devlog channel if not found in cache

bot/bot.py, bot/exts/easter/egg_facts.py, bot/exts/evergreen/branding.py, bot/exts/halloween/spookysound.py, bot/exts/pride/pride_facts.py
Closes #394
The above linked issue gives an explanation of the motivation to port over this functionality from the Python bot repository. Additionally, @SebastiaanZ has provided an excellent technical explanation of the problem that we're dealing with - thanks Ves!
In df17366, I have adapted [Mark's implementation](https://github.com/python-discord/bot/blob/master/bot/bot.py#L104-L143) from the bot repo. I've decided to simplify the implementation a little bit - the original will attempt to dispatch a warning webhook if the `on_guild_available` callback fires, but the received guild isn't fully ready yet. I do not personally think this is necessary, as we now have Sentry in place and a warning log should suffice.
In fd466d0, current calls to `wait_until_ready` are switched to the new …
=> Wait until guild ready

bot/__init__.py
Fixes #409 
Sets the event loop to Selector to prevent bot crashes on windows when an aiohttp request is made, as described in #409 
Same implementation as in https://github.com/python-discord/bot/pull/903
=> Set ayncio event loop to Selector on windows.

bot/bot.py
Closes #404 
This will hint users at the help command, while also showing what the prefix for SeasonalBot is. We emulate the main bot's message for the sake of consistency:
=> Show bot prefix in rich presence

bot/exts/halloween/halloweenify.py
Closes #402
This PR adds proper fallback messages when the halloweenify command is invoked by a member staff or through DM.
The bot doesn't have enough rights to modify staff nicknames, and can't change it when it is invoked through DM neither.
In-server usage.
Staff uage.
In DM usage.
=> Handle staff users and DMs in the halloweenify cog

bot/exts/evergreen/minesweeper.py
If the user trying to start Minesweeper has DMs disabled
then warn him in the channel where the command was
invoked.
Closes #399 
To fix this we check for `discord.errors.Forbidden` after sending the DM and inform the user if he has DMs disabled.
Currently if user has DMs disabled the script fails silently without informing him of any issues.
=> handle disabled DMs when starting Minesweeper

bot/exts/christmas/adventofcode.py, bot/exts/easter/april_fools_vids.py, bot/exts/easter/egg_decorating.py, bot/exts/evergreen/branding.py, bot/exts/evergreen/magic_8ball.py, bot/exts/evergreen/recommend_game.py, bot/exts/evergreen/snakes/converter.py, bot/exts/evergreen/speedrun.py, bot/exts/evergreen/trivia_quiz.py, bot/exts/halloween/candy_collection.py, bot/exts/halloween/hacktoberstats.py, bot/exts/halloween/halloween_facts.py, bot/exts/halloween/halloweenify.py, bot/exts/halloween/monstersurvey.py, bot/exts/halloween/spookyrating.py, bot/exts/pride/drag_queen_name.py, bot/exts/pride/pride_anthem.py, bot/exts/pride/pride_facts.py, bot/exts/valentines/be_my_valentine.py, bot/exts/valentines/lovecalculator.py, bot/exts/valentines/myvalenstate.py, bot/exts/valentines/valentine_zodiac.py, bot/exts/valentines/whoisvalentine.py, bot/utils/persist.py
- Cleanup: Add explicit encoding on open() calls #334
- Files without an encoding specified may crash bot #411
Closes #334 
Closes #411 
Added explicit encoding to `utf8` for cogs that open json or other text files.
Though this did not cause errors in Unix based OS, it was causing errors when loading some of those files in windows OS.
We may require explicit encoding going forward for other cogs being added to the bots that needs to read in a file.
=> Encoding bug fix

bot/exts/evergreen/status_cats.py
Closes #423 
I've added a command called `"http_cat"` with an alias `"statuscat"`. It recieves an integer from a user, then processes it through `http.HTTPStatus` to see if the status code actually exists. If it does, the URL will be valid and a picture will be displayed within an embed. If not, the embed won't show an image and instead it will tell you that the status code provided does not exist.
Instead of using `aiohttp` with a `ClientSession` to get information from the URL, I simply used the URL as the image within the embed.
When using a browser you can type in any code or string into the `code` section of the f-string `embed.set_image(url=f'https://http.cat/{code}.jpg')` and it will give you a 404 image. For whatever reason the image will not be put into the embed. Setting `code` …
=> Created the statuscat command.

bot/exts/evergreen/fun.py
Using a user token, a user could fetch the message ID of a message in any channel, which may leak information when potential Message objects are automatically converted and parsed.
Now, the bot will only retrive text from a valid Message object if the user has read permissions for the message the channel is in.
=> Stop users from viewing messages they shouldn't.

bot/exts/evergreen/fun.py
Description
This PR introduces sanitisation of the uwu text before uwufication in order to prevent moderator roles being pinged unnecessarily.
I've just changed the `str` typehint to the `clean_content` converter to do this as simply as possible.
While we do have a global limit to allowed roles being pinged in the bot, all mod+ roles were still capable of being pinged through this method.
**Before** (role resolves)
**After** (role is now plaintext)
=> Prevent uwu output from pinging globally allowed roles.

Pipfile, Pipfile.lock, bot/exts/evergreen/8bitify.py
This PR updates Pillow to 7.2.x. 
~~This currently breaks `8bitify`.~~ now fixed.
=> Update pillow to 7.2

bot/exts/halloween/hacktoberstats.py, bot/exts/halloween/timeleft.py
This PR fixes a set of issues with the Hacktoberfest commands.
- It allows the commands to be used in September and November so that the early start and late finish (Hacktoberfest starts and ends where it is October anywhere in the world) are factored in. This is also relevant because Hacktober now uses September as "Pre-temper" where maintainers should get issues ready.
- Updates the Hacktoberfest command branding to 2020
- References that you can also plant a tree
- Updates the timeleft command to use the Hacktoberfest dates, not just the month of October.
=> Hacktoberfest fixes

bot/exts/halloween/hacktoberstats.py
The `.hackstats` command logs an error when a given username does not exist on GitHub. This is not an actual issue, so we want to avoid logging this as an error. To prevent this, we should check the user exists before searching for their PRs.
I've also added authentication to the GitHub API requests in this cog and slightly changed the user agent.
Closes #467.
=> Hacktoberfest Stats: Check GitHub user exists before searching for PRs

bot/exts/halloween/hacktober-issue-finder.py
Closes #486 
This PR puts a limit on how long the response sent by the `.hacktoberissues` is going to be by limiting the issue body up to it's first 500 characters. This avoids http 400 errors (see #486 ) when dealing with issues with very long body.
=> Limit issue body to 500 characters

bot/exts/evergreen/snakes/_snakes_cog.py
Closes #490
After testing, I found that `urllib.parse.quote` is parsing spaces to `%2520%` that YouTube API don't support. Changing this to `urllib.parse.quote_plus` make this parsing spaces to `+` what YouTube API can read and then return again proper response with `items` key defined.
=> Fix snake video command

bot/exts/evergreen/fun.py
The `.roll` command now has a single space between the outputted dice, when more than 1 roll is specified. The code behind the command is also a lot more refined.
Previously, when given a number greater than 1, the `.roll` command sent the dice without space between them. This resulted in it looking quite strange.
Current:
Proposed:
=> Add space between dice in roll command

bot/exts/evergreen/fun.py
The command previously sent `!` as the prefix, while `.` is the correct one. Now imports prefix from `bot.constants`, so it'll always be up to date.
**Previous output:**
**New output:**
=> Change error message for roll command to use the correct prefix

bot/exts/halloween/hacktoberstats.py
hot fix for the `hackstats` command
it was raising key error:
and it seems that `item` was wrongly passed to `_is_accepted` and it should be `itemdict`
now it works for users that need checking for acceptance
=> fix keyerror for hackstats

bot/exts/halloween/hacktoberstats.py
- Updated PRs 'created' time range to the range @mattipv4 told me
- updated categorising prs logic, now PRs that are after the review period but created before october 3rd will count
for some people the PRs listed wasn't the same as the ones on the website, those PRs are the ones from before october 3rd, and passed review period. Now it's listed
Before/after
- ~~If dependencies have been added or updated, run `pipenv lock`?~~
=> Hackstats: fix time and date specifics

Pipfile, Pipfile.lock, bot/bot.py
After https://github.com/python-discord/bot/pull/1196, we should make sure SeasonalBot is also ready for the upcoming gateway intents changes. This PR actions the dependency upgrade.
~~Amongst @python-discord/core-developers we need to decide whether we will require the priviledged members intent as we do for the Python bot. If we do not use it, the (default) member converter will not work, and it will therefore not be possible to convert user IDs into Member objects.~~
With discord.py [`1.5.1`](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-1), the Member converter now does lazily fetch Member instances if necessary, so that should allow us to circumvent this issue entirely. I have adjusted the PR to bump directly to `1.5.1`.
Feel free to push commits to this PR.
=> Bump 'discord.py' to 1.5.1 and use explicit intents

bot/exts/halloween/candy_collection.py, bot/resources/halloween/candy_collection.json
Closes #495, #477 and #284 
The older code was storing candy spawn information in the json, which I think is unnecessary. I have replaced it all with two `set`s- `candy_messages` and `skull_messages` which contain the message ids of the messages where the spawns were made and pop them out when someone reacts to it.
The old schema looked like-
```json
{
"msg_reacted": [
{
"reaction":" \ud83c\udf6c",
"msg_id": 514442502460276740,
"won": true,
"user_reacted": 721012149933310029
}
],
"records": [
{
"userid": 721012149933310029,
"record": 2
},
]
}
```
Which is now simplified to-
```json
{
"records" : {
"721012149933310029": 2
}
}
```
Which makes it simple to group the score in leader-board (which was what wrong in the issue #495)
I think there is no reason for the spawn data to be in the json, …
=> Fix candy mini-game to group leader-board scores correctly

.github/workflows/lint-build-deploy.yaml
We're no longer using DockerHub in our deployment for SeasonalBot, so it does not make sense to keep pushing containers there.
=> Remove DockerHub from GitHub Actions

.github/workflows/build.yaml, .github/workflows/lint-build-deploy.yaml, .github/workflows/lint.yaml, bot/exts/evergreen/branding.py, bot/exts/halloween/candy_collection.py, bot/exts/halloween/hacktoberstats.py
This PR makes two changes to our CI:
Unfortunately, the flake8 action we were using from the marketplace required us to use the `pull_request_target` event, which runs in the context of the target repository to protect secrets. However, this also meant that flake8 would run on files already merged into our master branch, not the actual changes made in teh PR! That's obviously pretty useless as a guard against merging linting errors into our repository.
This change sidesteps the issue by removing the marketplace action and replacing it by a direct `flake8` run command. To make sure error output ends up as a GitHub Actions Annotation, we ask `flake8` to format its error messages using the correct GitHub Workflow Command format:
```
::error file={filename},line={line},col={col}::{message} …
```
=> Fix flake8 check in CI and separate Lint and Build jobs into separate workflows

.github/CODEOWNERS, .github/workflows/review-check.yaml
This commit adds a workflow that checks if a pull request has received at least one approval from a core developer. If not, the check will fail and block us from merging the Pull Request.
The reason we're adding this check is because we're moving away from making the entire Core Developers team a "code owner" of every line in every repository. This created a lot of "notification" spam, which drowned out the actually relevant notifications.
As we still want to make sure that there's at least one approving core developer, we now solve this using a workflow that checks for core dev approvals.
**Note:** I've annotated the workflow file itself extensively with comments. I've opted not to repeat that information here in the body of the pull request.
=> Add check for core dev approvals on pull requests

bot/exts/evergreen/error_handler.py, bot/exts/evergreen/snakes/_snakes_cog.py
closes #538 
Error handler now checks if the error has the attribute "handled" for locally handled errors instead of checking if the command has the attribute "on_error".
=> Modify error handler check for locally handled errors.

.github/workflows/build.yaml, .github/workflows/sentry_release.yaml, Dockerfile, Pipfile, Pipfile.lock, bot/__main__.py, bot/constants.py
Approved in #dev-core.
- Bumped Sentry SDK version from `0.14` to `0.19`.
- Added Redis and aiohttp integrations to Sentry SDK initializing.
- Added workflow for creating Sentry releases (based on site's one).
=> Sentry SDK version bump, integrations adding and Sentry release workflow

.pre-commit-config.yaml
Exactly the same changes as [PR 1334 on bot](<https://github.com/python-discord/bot/pull/1334>).
An old pipenv bug was eventually resolved, breaking precommit running properly within PyCharm. Setting `language: system` removes the need to set `os.putenv('PIPENV_IGNORE_VIRTUALENVS', '1')`, since `PIPENV_IGNORE_VIRTUALENVS` now defaults to being unset.
Success with this fix is documented within this screenshot, by adding an extra newline (for a total of 3), which flake8 rejects.
=> Make flake8 properly run through pre-commit in PyCharm.

bot/exts/evergreen/8bitify.py
Close #431
Removed default parameter override.
The default option for `colors` is 256, the number of colours 8-bit graphics has.
Before:
After:
=> Actually use 256 colours

bot/constants.py, bot/exts/evergreen/game.py
Closes #548
1. Changed env vars from a single api token, to the client id and client secret 
2. Added a background task to the Games cog to re-fetch an OAuth key before the current one expires, currently set to do it 2 days before expiry, but can be easily changed if we want more notice.
3. If first attempt to get OAuth access token fails, unload the cog.
4. If attempts to renew OAuth access token fail, raise error but continue to use current token.
5. Delay the start of the `refresh_genres_task` until we get an OAuth access token.
6. Change all `get` requests to `post` requests.
1. This is required by the new OAuth flow of V4
2. Instead of using a set period of time and using a `@task.loop()` a background task like this allows us to vary the amount of time between expiry and when we …
=> Migrate to IGDB V4 API

bot/resources/evergreen/trivia_quiz.json
=> some new questions

bot/exts/evergreen/cheatsheet.py
Fixes `cheatsheet` command, which was sending raw html output as [`cht.sh` ](https://github.com/chubin/cheat.sh) had reverted the change of `aiohttp` User Agent. To fix this, I have added `curl/7.68.0` as the User Agent which is being passed through `headers`.
**Before:**
**After:**
=> Add curl User Agent Headers

bot/exts/evergreen/wolfram.py
Previously the server IP address could be leaked using some query such as “what is the weather here?” or simply “what’s my ip?”. This aims to fix it by using mock locations.
=> Add location mocks to the wolfram cog

Pipfile.lock, bot/exts/evergreen/xkcd.py
Closes #588. 
I set the description the the alt key in the json page, and set a url in the title to the link to the comic.
The `alt` key from the request was already available, and could be safely added to the embed. The URL was also available.
**Before Changes :**
**After Changes: **
=> Added description and url to embed of xkcd command

bot/exts/valentines/be_my_valentine.py
By raising `UserInputError` the `on_command_error` listener `bot/exts/evergreen/error_handler:43` will reset the command cooldown and output a usage embed. By passing the error message as a string to `UserInputError` it now gets displayed within the same embed, rather than two messages.
The reset cd already exists functionality, so raising the error utilizes already implemented & tested code.
Usage embed when sending to yourself
Usage embed when sending to someone with DMs disabled
Usage embed when sending to someone without lovefest role
=> Reset valentine command cooldown on failure

bot/constants.py, bot/exts/evergreen/wikipedia.py
Closes #565 
This has been implemented with help of `aiohttp` to request and get json data of the Wikipedia Article. It then filters the data and stores only the required information namely `Title`, `Snippet` and `Page ID`. This filtered data to the Line Paginator.
Approved by Staff Member.
=> Improve Wikipedia Command

bot/bot.py
Closes #606
Uses `channel.id`s instead of `channel` object while checking for missing channels. Skips the check if `debug` is set to `False` in the `.env`.
=> Fixes Startup Channel Check Bug

bot/constants.py, bot/exts/evergreen/pythonfacts.py, bot/resources/evergreen/python_facts.txt
Closes #587 
I added a text fie with some facts and made the command send an embed with the fact.
The text file would be simplest to edit and change.
=> Add .pyfacts command

bot/exts/evergreen/tic_tac_toe.py
I changed the code up a bit,
So when the user tries to play the game with an opponent,
The program would first check whether the _opponent_ is a bot or not.
If the bot is a opponent, then game would not start, instead
a message saying: `"You can't play Tic-Tac-Toe with bots!"` would be sent
I also made a new alias called `tic`
=> Added another alias and fixed a bug in Tic-Tac-Toe

bot/exts/christmas/advent_of_code/_cog.py, bot/exts/evergreen/emoji.py, bot/exts/evergreen/game.py, bot/exts/evergreen/minesweeper.py, bot/exts/evergreen/movie.py, bot/exts/evergreen/snakes/_snakes_cog.py, bot/exts/evergreen/space.py, bot/exts/evergreen/status_codes.py, bot/exts/utils/extensions.py, bot/exts/valentines/be_my_valentine.py, bot/utils/extensions.py
Closes #624 
I've changed all the `ctx.send_help`'s to `bot.get_command("help")` and `ctx.invoke(help_command, ctx.command.name)`.
It looks a lot better.
Before:
After:
Affected commands are `.games`, `.snakes`, `.space`,  `.emoji`, `.minesweeper`, `.movies`, `.status`, `.extensions` (and its subcommands), and `.bemyvalentine`.
=> change ctx.send_help to ctx.invoke(help_command)

bot/utils/decorators.py
Closes #556
Remove all default whitelisted channels from the channel kwarg before building the output string
Previously this would output all channels, and could result in an error. This change ensures only the main bot channel & and any overridden channels are shown in the embed. We do this before the categories block as the categories kwarg itself is an override, so we want to include those in any output.
Example where there are no overrides:
Example where whitelist includes overrides:
=> Only output override channels & bot commands channel on whitelist error

.github/workflows/build.yaml
Internal decision to migrate, no issue open.
GITHUB_TOKEN has now enough permissions to be used for pushing to GHCR, so we don't need PAT anymore.
=> Migrate GHCR_TOKEN -> GITHUB_TOKEN in Docker build action

bot/exts/evergreen/8bitify.py
Instead of using the cached user the bot now explicitly fetches the user from the API to get the most up to date profile info
This is because some API events arent going through on pydis (user_update) and the cached user isnt being updated with a new avatar
=> fix: use get_user in 8bitify to avoid events issues

bot/exts/evergreen/issues.py
Currently repos such as quackstack don't work with the issues cog when typing, for example, quackstack#29 into discord, since by default GitHub paginates repos to 30 per page, and we only fetch one page.
Reasoning is to make the functionality work for repos beyond the 30 repo pagination limit, by adding a per_page query string to get 100 per page. This is not a permanent fix, but it should certainly suffice for a long time - another 64 repos.
=> Fix issues with repos not working when typing repo#num

bot/exts/evergreen/issues.py
Add `\b` characters around the issues regex
So we only respond to issues if the regex fully matches a word.
EG sir-lancsdrbot#1 would match bot#1, whereas now it wouldn't match at all.## Did you:
=> Add word boundaries to the issues regex

bot/constants.py
Added an environ.get with a default value
Allows users to override the default emoji to their own, which will avoid errors in dev testing.
=> Add an env var for trashcan emoji override

bot/exts/evergreen/timed.py
Implements and closes #671 
The changes have been implemented by creating a new execution context for the command by taking the message content, updating a copy of the message with that content, and using `bot.get_context()` to get a new context for execution. The invokation of that context is then timed by perf_counter() and displayed to the user upon the command finishing with the time in seconds to .4f precision.
It's been implemented in this way so as to be able to display the time without modifying the original context,
A normal timed execution:
An attempt at timed execution where command permissions were denied (temporarily role-gated 8bitify command):
An attempt at timed execution where the command is on cooldown (temporarily cooldowned 8bitify command):
Passing additional command …
=> add timed command for timed execution of commands

.gitignore, Pipfile, Pipfile.lock, bot/exts/evergreen/latex.py
Closes #663 
Uses matplotlib's default parser for rendering tex.
matplotlib's subset of tex allows nothing more than symbols and alphanumeric characters, eliminating the need for sandboxing.
It also does not require a local installation of LaTeX.
=> Add latex cog

bot/exts/easter/april_fools_vids.py, bot/resources/easter/april_fools_vids.json
A simple fix to put videos in their correct channel names to avoid this:
=> fix: put april fools video links in correct channel names

bot/exts/evergreen/issues.py
fixes it being unable to get issue numbers larger than 9
limits it somewhat length-wise and character-wise to the actual github limits
Changed the regex to match numbers at the end greedily
Changed the regex to only match allowed characters
regex used: https://regex101.com/r/V2ji8M/6
=> Fix issue matching regex

bot/exts/evergreen/ping.py
No github issues, but the relevant conversation in pydis/dev-contrib is around here https://discord.com/channels/267624335836053506/635950537262759947/831533475760832603
A simple command that sends an embed showing the bot's websocket latency. It is simple as was discussed; it has no need to be complex, just provide basic information and more importantly show that the bot is online.
=> feat: add ping command

bot/exts/evergreen/error_handler.py, bot/exts/evergreen/timed.py
When a new execution context is created in the timed command it's now added as the `subcontext` attribute of the parent context. When the error handler deals with the error the context is set to the subcontext if available, else the normal context. This means the command displays correctly.
It's been implemented this way since I believe it to be the cleanest and simplest way to do this. If this turns out not to be the case I'm more than happy to change the implementation to something more suitable.
Before:
After:
=> fix: display help for the correct command when an error occurs in timed

bot/exts/evergreen/catify.py
I indented some code into the `else` statement because some variables that were defined in it were used outside of it, and suppressed `discord.Forbidden` when someone with a higher role than Sir Lancebot uses the command.
=> Fixed the .catify command producing UnboundLocal and Forbidden Errors

bot/exts/easter/egg_decorating.py, bot/exts/evergreen/catify.py, bot/exts/evergreen/fun.py, bot/utils/helpers.py
Closes #703
I've added a helper that does a regex search through a given string, looks for `http` or `https`, and surrounds that with `<>`. I've called it in places I could find where the bot tries to echo part of, or the full user input back to the user.
Regex seemed like the most simple way to deal with finding links. This solution does not take into account that an already escaped link will end up with weird extra brackets around it, but that didn't seem to matter much.
=> Suppress Links In Certain Commands

bot/exts/evergreen/reddit.py
Closes #701
Changed a list slice from `[1]` to `[0]`.
Added a min check for length of the respond, before shuffling. 
If a subreddit has <2 posts, the posts[1] check would fail with an IndexError.
If the subreddit had less than 5 posts, then the k=5 check would also error. These changes harden the command for these edge cases.
=> Fix errors when a subreddit has <5 posts.

bot/exts/evergreen/avatar_modification/avatar_modify.py
Closes #712 
Removed `()` from the allowed filename characters since they cause issues in Discord with the file showing outside of the embed.
Before; 
After:
=> fix: remove () from list of safe filename chars

.github/pull_request_template.md
Fixed a spelling mistake in the PR template (tempelate -> template). Was discussed [here](https://discordapp.com/channels/267624335836053506/635950537262759947/837756009992028180).
=> Fix the spelling mistake in the PR template

bot/exts/evergreen/catify.py
Discussed [here](https://discordapp.com/channels/267624335836053506/635950537262759947/839515870937088052).
This PR adds a 1 use every 5 seconds cooldown per user to the `.catify` command to avoid spamming it.
=> Add a 5 second cooldown per user to .catify

bot/exts/evergreen/avatar_modification/_effects.py, bot/exts/evergreen/avatar_modification/avatar_modify.py
Closes #687 
Continues #688
This PR adds the `.mosaic` command, which splits your discord avatar in the amount of squares you provide, the maximum being `10000`.
=> feat: Add the .mosaic command

bot/exts/evergreen/avatar_modification/avatar_modify.py
Fixes the check on the `.mosaic` command, which is missing a `not`.
=> Fix the .mosaic command check that is missing a `not`

bot/exts/evergreen/avatar_modification/avatar_modify.py
This is because discord.py would populate the user portion of the fetched member with cached information which would cause the avatar url not to be updated as we had intended with that function.
=> Switch from fetch_member to fetch_user in avatar_mod

.github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/sentry_release.yaml, .github/workflows/status_embed.yaml
This grouping means any new actions on either a PR or against main, will cancel any running actions.
We do not care about these old actions, as they are out of date, so cancelling them will mean the actions we do care about get done faster.
=> Add concurrency behaviour to github actions

bot/exts/evergreen/latex.py
As we are currently working on restricting resources on the latex cog, this commit will prevent it from loading.
It will be reverted once solved.
=> Latex: temporarily disable loading of the cog

bot/exts/evergreen/trivia_quiz.py
Closes #739 
This PR handles a `KeyError` in a race condition for `.quiz stop`. Just a `try/except`.
=> fix: Handle a KeyError when using .quiz stop

bot/exts/evergreen/source.py
Currently, when you do `.source help`, it sends the description of [`bot.command.Command`](https://github.com/python-discord/bot/blob/main/bot/command.py#L4-L11), instead of the actual help command. This is because of this line:
https://github.com/python-discord/bot/blob/67934bd582ae5a6fac459c02ba3fa6c17d085d1a/bot/exts/info/source.py#L112
Since our help command is just a regular command, I removed the check to see if the source item is a help command.
Before:
After:
=> fix: Send the right help message for `.src help`

bot/exts/evergreen/status_codes.py
These status dog codes aren't server-friendly, so we use status cat instead.
=> Forward some status dog codes to status cat instead

docker-compose.yml
Since we use the same port for redis on all out projects, having this always restart causes conflicts for people starting up docker and wanting to use redis for any other project.
=> Change to unless-stopped restart policy

bot/exts/evergreen/tic_tac_toe.py
Closes #771 
In tic_tac_toe.py, I changed the description being returned in the embed for the show_tic_tac_toe function from - 
`description=f"{game.winner} :trophy: vs {game.loser}\n\n{game.format_board()}"`
to - 
`description=f"{game.winner} vs {game.loser} (draw)\n\n{game.format_board()}" if game.draw else f"{game.winner} :trophy: vs {game.loser}\n\n{game.format_board()}"`
where it checks for the draw condition of the respective game before evaluating the value of embed.
=> embed displays draw condition on show command

bot/constants.py, bot/utils/checks.py
> It is mandatory to link to an issue that has been approved by a Core Developer, indicated by an "approved" label.
Issues can be skipped with explicit core dev approval, but you have to link the discussion.
Uh, well, actually technically I didn't do that, sorry 😢 
I added permissions for members to run sir-lancebot commands in their codejam team channels. I added a constant with the name of the category, and added the check to the `in_whitelist` check function.
- [no] Ensure there is an issue open, or link relevant discord discussions?
=> Allow commands in code jam team channels

.github/pull_request_template.md
The contributing guidelines also contain a part which requires contributions to follow the open source license. 
This requires the user to agree that they do follow said guidelines when making a pr.
=> Make user affirm their pr follows guidelines

bot/exts/valentines/lovecalculator.py
This makes a few changes to the `.love` command to make it slightly less creepy, more consistent with other lovefest commands and also makes it give consistent output, regardless of input order.
The changes I have made are:
- Added and `in_month` check, to ensure the command can only run during February (valentine season)
- Require that both members have opted into the love fest event (by checking roles)
- Sort the members to be checked before hashing, to ensure symmetrical results.
- Removed some now un-used checks since we don't accept arbitrary strings as input
=> Love command checks

bot/resources/evergreen/py_topics.yaml
Continuation of https://github.com/python-discord/sir-lancebot/pull/763.
=> More topics to start Python-related conversations with.

bot/exts/evergreen/snakes/_utils.py
Details : https://github.com/python-discord/sir-lancebot/issues/821
Closes #821 
The snake was added in the _utils file and is implemented through a linking of a igmur image
=> Add baby anaconda to snake hatch

bot/exts/evergreen/bookmark.py
Closes #811
Allows the execution of the `.bm` command by users in help channels.
=> Whitelist `.bm` command in occupied help channels

bot/exts/evergreen/realpython.py
Added the "kind": "article" parameter to the API request. This should only return articles to the user instead of courses, lessons or quizzes.
Also updated the "Here are the top x results" message to handle a variable amount of articles.
[Ticket: python-discord#828]
Closes #828
=> Only send articles to user - Closes Issue#828

bot/bot.py, bot/exts/easter/egg_decorating.py, bot/exts/evergreen/avatar_modification/avatar_modify.py, bot/exts/evergreen/bookmark.py, bot/exts/evergreen/recommend_game.py, bot/exts/evergreen/snakes/_converter.py, bot/exts/evergreen/snakes/_snakes_cog.py, bot/exts/evergreen/snakes/_utils.py, bot/exts/utils/extensions.py, poetry.lock, pyproject.toml
Since the Discord.py repository has been archived, we can switch to the latest commit of 2.0a0, knowing no breaking change will occur (still pinned to the commit just in case).
This commit also solves two small problems due to that fix, the avatar interface changing and Embed.name disappearing. Quite a painless migration.
I took the liberty of adding two QoL things:
- Adding mentions as a valid trigger for the bot
- Making the bot automatically join new threads
=> Migrate to Discord 2.0a0

bot/exts/evergreen/bookmark.py, bot/exts/evergreen/fun.py
Closes #837 Closes #840
`discord.Member.permissions_in()` was removed in d.py 2.0 in favour of using `discord.Channel.permissions_for` everywhere.
=> Use permissions_for over permissions_in

.github/workflows/lint.yaml, poetry.lock, pyproject.toml
Port of https://github.com/python-discord/bot/pull/1779
---
Since our project is licensed under the MIT License, we can't be using any incompatible license-wise dependencies in our project, such as GPL.
This commit adds a step to the CI lint phase that will use pip-licenses to verify that all the installed packages are part of an ALLOWED_LICENSE variable. This variable is currently set to be every license we currently use.
We opted to use an allowlist instead of a denylist to make sure that new licenses are reviewed by hand and added to that variable.
=> CI: check license compatibility

bot/exts/fun/trivia_quiz.py, bot/resources/fun/trivia_quiz.json
Closes #446 
Tis PR adds the wikiguess game. To implement this I have used the random wikipedia article API, to get the title, extract. The questions are formed using the extract, which is then run through a replace function, to remove the title if it is present in the extract with `[redacted]`. 
Another check I have added while fetching the wikiguess question, is to check whether the title contains any non alpha-numeric character (`-+-*/[]{}()!@#$%^&`). As it becomes difficult to answer when the answer is like "Felsőkelecsény" or " Camp Lake, Wisconsin" and you answer "Camp Lake".
=> Wikiguess Game

bot/exts/holidays/hanukkah/hanukkah_embed.py
This is a solution for the #862 issue, which says the Hanukka holiday can also be in November and not only in December.
Closes #862 
I added the Hanukka command in November month, by adding Month.NOVEMBER to the in_month decorator.
=> Added Hanukka command in November month.

bot/exts/fun/hangman.py
Closes #871
With multiplayer and a missing check for the right channel the bot would respond to each message as one directed to the game. Multiplayer mode is planned to be reintroduced later on using threads (tracked in #872).
=> Remove multiplayer mode and correctly check current channel

bot/constants.py, bot/exts/utilities/bookmark.py
Closes #827
Allowed the `.bm` command to be used everywhere by using our whitelist overrider.
=> Allow everyone to use the `.bm` command everywhere

bot/exts/events/hacktoberfest/hacktober-issue-finder.py, bot/exts/utilities/emoji.py
You know the drill, due to discord.py 2.0a0 datetimes are now offset-aware, breaking some code.
Closes python-discord/sir-lancebot#875
=> Make the discord.py datetimes offset-naive

bot/exts/holidays/halloween/spookyreact.py
Spooky reactions are now limited to users. The example below was previously possible, but won't happen anymore:
The bot previously only ignored its own messages, but now ignores messages from all bots. Even though we love our bots, they simply aren't supposed to be a part of this Halloween tradition. Sorry Xith!
=> Ignore all bot messages for spooky react

bot/exts/holidays/valentines/lovecalculator.py
Closes #784 
I removed the `-1` from the quote index calculation at <https://github.com/python-discord/sir-lancebot/blob/3218ff7d59c9db211039414b8c84ea098fd784d6/bot/exts/valentines/lovecalculator.py#L75> This means the command `[p]love` (`[p]` refers to Lancebot's prefix) will now return the correct quote for `love_percent = 0` edge-case, and scores in the range [96, 100] will now correctly use the 100 quote from `bot/resources/valentines/love_matches.json` instead of the 95 quote.
=> Correct an off-by-one bug due to bisect.bisect()

bot/exts/holidays/halloween/candy_collection.py
[Approved by core dev to PR without issue](https://discord.com/channels/267624335836053506/635950537262759947/903279888495157329)
Check whether a reaction is for a bot message when adding candies upon reactions. Previously you could use bot's reaction buttons which would trigger `on_reaction_add` and have a high chance of getting candies (or skulls). It can easily be abused to spam reactions, which apparently doesn't trigger an auto-mute like spamming messages do, AFAIK.
It can be tested using commands that has bot reaction buttons like `.help` or `.ttt`.
I don't really like the fact that reaction triggers have a higher chance to get candies (even though sure reactions are rarer than messages). There's still a way to spam candies, but normal users are quite unlikely to figure out how. But …
=> Candy Game: Ignore reactions to bot messages when adding candies

bot/exts/utilities/realpython.py, bot/exts/utilities/wikipedia.py
Closes #940 
Now the `.rp` command has option to get specific amount of articles in between 1-5 (inclusive). I added new parameter to `.rp` which is `amount`. If no argument given when command is ran, the default value 5 will be used. If user tries to give negative, 0 or bigger than 5 , the bot will send a message saying "`amount must be between 1 and 5 (inclusive).`".
=> Add option to get specific amount of articles

bot/exts/utilities/wikipedia.py
Close #933 
I added `restrict_to_user=ctx.author` to wikipedia.py. Limits user reactions to prevent non-author from removing message by adding user restriction to paginator.
=> Limit user reactions on embed pagination

bot/exts/utilities/wtf_python.py
-Added a default value to `query`, and if the value is None, send the
link to the repository in an embed.
-Modified the if / else statements to if / elif / else with the new
if statement to check if the value of `query` is None.
Closes#938
-Added a default value to `query`, and if the value is None, send the
link to the repository in an embed.
-Modified the if / else statements to if / elif / else with the new
if statement to check if the value of `query` is None.
=> Handle `.wtf` command without query

bot/__init__.py, bot/__main__.py, bot/constants.py, bot/log.py
The most recent changes to the logging setup were crashing the bot on startup in prod, as `/logs` was read-only. This PR prevents any file logs from being written in prod, since we don't use them anyways.
This PR also moves the sentry setup into the init, so we can catch any errors that happen before we get to main (such as the one behind this bug). It's not best practice for the `__init__` to have side-effects, but it really doesn't matter in this case.
=> Fix Startup Crash Loop

bot/exts/events/advent_of_code/_cog.py, bot/exts/events/advent_of_code/_helpers.py
Closes #325 
- The AoC day and star browser has been separated from the leaderboard command, from now on it's a separate command
- The leaderboard command has a new `self_placement_name` option, that shows the personal stats for the specified profile name.
=> Introduce command changes in the AoC Cog

bot/exts/avatar_modification/avatar_modify.py
Discussion: [https://discord.com/channels/267624335836053506/635950537262759947/912443523029168168](url)
This PR is simply to fix a grammatical mistake in the description ("brief") of the `.spookify` command on Sir Lancebot.
=> Fix a grammatical mistake in the description of the `.spookify` command

bot/exts/events/advent_of_code/_cog.py
Swapped out our custom logic to create a human readable delta with a Discord time stamp.
This allows users to hover over the time stamp to get an exact date, along with automatically rounding to the most significant unit.
I have also added a refactor commit to swap the conditional block around, so the "smaller" code path is the one in the if statement, which makes the function easier to read.
Before:
After:
Discord time stamps round, rather than truncate like we were doing previously, which is why this says 2 days, rather than 1.
=> Aoc count timestamp

bot/exts/holidays/hanukkah/hanukkah_embed.py
https://canary.discord.com/channels/267624335836053506/635950537262759947/915621871960092712
rewrote hanukkah to use datetime.strptime
left a helper method and some variables in order to allow extending
to use a cache in the future, rather than requesting the api every invoke
that is out of scope of this commit and pull, since the command is
currently broken.
I've only kept the same functionality, without trying to rewrite the
entire command.
=> fix: hanukkah command respects month boundaries

bot/exts/events/advent_of_code/_cog.py
Approved by @janine9vn: https://discord.com/channels/267624335836053506/635950537262759947/915806212367482891
Closes #962
I made `.adventofcode leaderboard`'s `self_placement_name` argument keyword-only to accept multi-word usernames without needing quotation marks.
=> Make self_placement_name keyword-only in .aoc lb

bot/exts/events/advent_of_code/_cog.py, bot/exts/events/advent_of_code/_helpers.py
This adds functionality to the Advent of Code cog for users to "link" their Discord Account with their Advent of Code name on the leaderboard. The cog doesn't explicitly make use of it, but it is necessary to exist and be functional for something I want to do. 
This is implemented with a Redis Cache. A user can link their discord account with a name they specify and it's stored as a key-value pair with the Discord ID as the key.
There is no validation that the name they are entering is on our leaderboard. This is an intentional decision as I don't want to rely on the leaderboard cooldown for a user to successfully run this command. If a user fucks up their name, that's on them. It does check if the name they are trying to link is already in the cache and provides the appropriate response. …
=> Add `.aoc link` command

bot/__init__.py, bot/exts/utilities/bookmark.py, bot/monkey_patches.py
Ported from https://github.com/python-discord/bot/pull/1990/
Discord.py's message converter is supposed to infer channelID based on ctx.channel if only a messageID is given. A refactor (linked below) a few weeks before d.py's archival broke this, so that if only a messageID is given to the converter, it will only find that message if it's in the bot's cache.
=> Fix message converter

bot/exts/utilities/colour.py
Context: https://discord.com/channels/267624335836053506/635950537262759947/909560534381252619
Added decorator to allow bot in the dev and media categories.
=> minor: allow color command in dev-media

bot/exts/holidays/halloween/candy_collection.py, bot/exts/utilities/issues.py
Closes #947 
Added user's score to Candy command by adding one additional function/variable, and including verbose to the candy commands message. Invoker of candy command will now see their candy score.
=> Added user's score to Candy Command - Closes #947

bot/constants.py, bot/exts/events/advent_of_code/_cog.py, bot/utils/members.py
This PR adds ~~an hourly task~~ a task that runs every 10 minutes to give a specific role to users who have completed all 50 stars and linked their Discord accounts. The role itself gives users a nice vanity role icon to show off their accomplishment.
This uses the cached leaderboard, so doesn't add any extra calls to the AoC API.
I have also added a command to block members from getting this role. This could be used where we have believe that the user in question didn't complete the stars themselves (such as copying answers from the internet).
=> Give AoC completer role to members with 50 stars

bot/exts/events/advent_of_code/_cog.py, bot/utils/members.py
This adds some logging to AoC role task to help with debugging issues, along with raising error when bot can't modify the given role in member helper util, rather than silencing it.
<–– Chris doesn’t have the authority to refuse––>
=> Add logging to aoc completer task

bot/exts/events/advent_of_code/_cog.py, tox.ini
This allows AoC commands to be ran in January, along with limiting AoC join to only be ran in Nov, Dec and Jan.
This also removes the aoc subscribe command, since Python has a replacement for it now.
=> AoC month changes

bot/exts/fun/game.py
Closes #995 
Closes SIR-LANCEBOT-7H
Added missing enums to `GameStatus`, `AgeRatingCategories` and `AgeRatings`.
=> Fix `ValueError` in game cog

bot/constants.py
GitHub updated their issue closed emoji from red to purple, this updates the emoji to relfect that new colour.
=> Update GitHub issue closed emoji

bot/exts/events/advent_of_code/_cog.py
Not using `.value` meant it was pulling the enum name, and therefore was failing the check.
=> Fix aoc join in date logic

bot/exts/events/advent_of_code/_cog.py
When a user doesn't set a name, the AoC API doesn't return a name key at all, so we need to make use of the ID field instead, to build the name based on a similar tempalte that AoC uses for it's leaderboard.
=> Fix AoC name lookup for anon users

bot/exts/utilities/epoch.py
Closes #1004 
Ignore `OverflowError` when parsing relative times. `BadArgument` is raised in the absolute time part of the converter if it cannot be converted there
=> fix OverflowError in epoch command

bot/exts/events/advent_of_code/_helpers.py
discussed on discord, using this implementation from zig: 
closes #967 
closes #966 (indirectly)
new embed: 
Edit: did not link the discussion: https://canary.discord.com/channels/267624335836053506/635950537262759947/916405655630389310
=> nit: make last refreshed time above the rest of the embed

.github/workflows/lint.yaml
This is caused by an upstream issue with setuptools 60.* (via virtualenv) changeing the default to using the setuptools-embedded distutils rather than the stdlib distutils, which breaks within pip's isolated builds.
This is explained quite well here https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763
=> setuptools use stdlib distutils over embedded

.pre-commit-config.yaml, bot/constants.py, bot/exts/events/advent_of_code/_helpers.py, bot/log.py, tox.ini
Approved by myself.
When browsing the prod logs looking for a specific error, I noticed that the AOC cog produced a bunch of mostly pointless logs which contributed heavily to making the logs unbrowsable. This PR removes the main offenders while not losing any important information.
This PR adds a few unrelated changes to the config, but they are minor and should be good overall. The commit message for those changes should explain everything.
=> Clean Up AOC logging

bot/exts/holidays/valentines/lovecalculator.py
https://discord.com/channels/267624335836053506/635950537262759947/937865211254304778
This changes two references in the `.love` command to point to `!subscribe` instead of the deprecated `.lovefest unsub` command.
=> Fix `.love` references to deprecated unsub command

bot/exts/events/advent_of_code/_cog.py
This disabled the completionist task that checks the leaderboard for people who have 50 stars and gives out the role. Since the event is running, we are not keeping the session cookies up to date, so this is flooding #dev-log with errors.
This task should be altered in preparation for next event so that commenting out this line isn't required.
=> Disable AoC completionist task

.github/workflows/lint.yaml, bot/__main__.py, bot/constants.py
This adds a step to our linting action to catch errors in imports/cog setup functions before they are merged by running the bot package, but not actually calling `bot.run()`.
Adding it to the lint flow means we already have the code checked out and a poetry env, so it adds ~1s to CI time.
See here fir a passing action https://github.com/ChrisLovering/sir-lancebot/runs/5264386120?check_suite_focus=true
This is a failing one https://github.com/ChrisLovering/sir-lancebot/runs/5264408507?check_suite_focus=true
=> Add run bot step during lint

bot/exts/core/internal_eval/_internal_eval.py
Close #990 
I have truncated the output using the shorten_output method, limit the output to be 99980* character.
(*) the reason why is it 99980 is there should be 20 charater in the end stating that the output was truncated, they are `\n[output truncated]`
=> truncate output.

bot/constants.py, bot/exts/fun/latex.py
Allows the latex command to be ran in the data science and AI channel, as this is the place most likely to want a latex command. More channels can be added to the tuple after this PR as needed.
Here it is in action (where I have used the dev-core-contrib channel in my test server in place of the data science and ai channnel)
=> Allow latex command in data science and ai channel

bot/exts/core/help.py
Fixes GH-1065. 
`parent` already has a trailing space so let's not add *another* one.
=> Help: remove redundant space in subcommand aliases

bot/exts/fun/uwu.py
Fixes #1069 
Updates `.uwu` to check for content in a replied to message if the current message is empty.
=> Update .uwu to work with replies

bot/exts/fun/uwu.py
Fixes #1072
6db84b38568d3f53c1b1bec4c66c1c8f2ee7b1ac
- Added pattern `REGEX_EMOJI` to capture emoji markdowns
- Implemented `Emoji` data class for emoji information and displayability inferencing
- Added function `_ext_emoji_replace` to replace external undisplayable emojis with random emoticons
- Added call to `_ext_emoji_replace` at the end of `_uwuify`
202d53b3f7ebe4d6041a2e5a4c1419bc16b27e11
- Added type checking annotations for `fun_cog` using `typing.TYPE_CHECKING`
21194a8817ee34229a211f6f5aae8978d054a884
- Replaced a redundant single-letter regex character class with the character itself
- Built-in emojis and emojis the bot is able to display (due to sharing a server) are returned normally.
- For external undisplayable emojis, the bot correctly replaces it with a random emoticon …
=> Fix: .uwu incorrectly transforms emojis in their raw text form

bot/exts/fun/fun.py, bot/exts/fun/uwu.py, bot/utils/messages.py
Closes #1075
In `uwu_command`, if command was invoked referring to a replied message, store the message's embeds in an `embeds` variable, otherwise set it to `None`.
Add an `else` statement in `uwu_command` after `if embed is not None` to fallback to `embeds` which was defined earlier.
Add a check in `uwu_command` to avoid adding a leading `>>>` if the uwuified content contains only an embed.
=> Fix issue with .uwu failing to uwuify embeds in replies

bot/exts/core/error_handler.py, bot/exts/core/help.py, bot/utils/commands.py
issue: #863 
Refer to https://github.com/python-discord/sir-lancebot/pull/884
- The help command used to raise an error when provided with an invalid command name (fixed)
- There used to be different command suggestions from the help command and the error handler when an unknown command was provided.
- This has been fixed by using the same method for finding similar commands.
- Providing an invalid subcommand but valid parent command (for example: `!ext listt`, ext is valid but subcommand `listt` is invalid) now sends the help command output for the parent command.
- Using `bot.all_commands` attribute instead of `bot.walk_commands()` generator.
- `walk_commands()` is not useful in the error_handler because (as it provides us with all subcommands also), when there is an invalid subcommand, …
=> Help command fix, normalize suggestions for unknown commands

bot/__main__.py
1<<15 is the flag for message content intent, so adding this value to the intents value hard codes that to always be enabled.
Doing it this way also bypasses the need to patch the flags themselvse in discord.py.
This is required until https://github.com/python-discord/sir-lancebot/pull/1092 is merged.
=> Add 1<<15 to the raw intents value

.github/workflows/lint.yaml, Dockerfile
Approved by myself and @ChrisLovering 
Poetry 1.2 introduced a regression which broke pip `--user` installs. These types of install were the main way we did installations in docker and CI, as they made it much more convenient to control the location, availability, and caching of packages.
Poetry's team does not recognize this as a supported use case, so major changes were required to get everything working again. Most of the changes were consolidated into chrislovering/python-poetry-base for docker, and HassanAbouelela/setup-python for CI.
This is part of a larger collection of PRs to python-discord projects.
=> Fix Poetry 1.2 Support

bot/exts/holidays/halloween/spookygif.py
> Corrects key values for Giphy API response in .spookygif command
> 
> ## Relevant Issues
> #1050
> 
> ## Description
> Made the following change to line 28 of bot/exts/holidays/halloween/spookygif.py
> 
> ```diff
> -url = data["data"]["image_url"]
> +url = data["data"]["images"]["original"]["url"]
> ```
> 
> ## Did you:
> * [x]  Join the [**Python Discord Community**](https://discord.gg/python)?
> * [x]  Read all the comments in this template?
> * [x]  Ensure there is an issue open, or link relevant discord discussions?
> * [x]  Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?
=> Fix issue #1050

bot/exts/fun/hangman.py, bot/exts/fun/madlibs.py
Closes #1106.
As the title says. `Client.wait_for` is now a positional-only arg, so adjusted as such to fix the games (tested and both games do now work).
=> Fix position-only arg in hangman & madlibs command.

bot/exts/events/advent_of_code/views/dayandstarview.py, bot/exts/events/trivianight/_scoreboard.py, bot/exts/utilities/epoch.py
Closes #1108.
During development of dpy 2.0, the order of the `interaction` and `select` swapped, but this wasn't updated in the codebase. This PR fixes that in the 3 use-cases of the `@discord.ui.select` decorator.
=> Fix order of function parameters on @discord.ui.select

bot/exts/events/hacktoberfest/hacktober-issue-finder.py
Closes #1107.
As described in the issue, the value of the `body` key returned by the API can be a literal `null` value, meaning `dict.get("body", "")` won't substitute as the key does exist. Instead, we now use `dict.get("body") or ""`.
=> Fix hacktoberfest-issues bug

.github/workflows/build.yaml
Solves part of https://github.com/python-discord/kubernetes/issues/140, since the repository is now public.
=> `REPO_TOKEN` is no more.

bot/exts/core/help.py
[Closes#1122](https://github.com/python-discord/sir-lancebot/issues/1122)
updated bot/exts/core/help.py file is updated as discussed in issue#1122
=> updated bot/exts/core/help.py for Issue #1122

bot/__init__.py, bot/__main__.py, bot/bot.py, bot/exts/core/extensions.py, bot/exts/fun/fun.py, bot/exts/fun/game.py, bot/exts/utilities/logging.py, poetry.lock, pyproject.toml
Bumps botcore from 8.2.1 to 9.3.1 (now called pydis-core)
=> Bump botcore version

bot/exts/holidays/holidayreact.py
None. I asked in python-general whether I should make this an issue first, but godlygeek and zig suggested its size (+3 characters) makes that unnecessary.
I accidentally told Sir Lancebot that Earth Day was in February, meaning that it is currently (during February) reacting on `earth`. This PR moves it to April, where Earth Day resides on the 22nd.
=> Move Earth Day Reactions from February to April

bot/exts/utilities/bookmark.py
**NOTE**
This needs to wait for [this PR](https://github.com/python-discord/bot-core/pull/171) before it can be merged, since it will be the one syncing the command tree.
Once that has been completed & merged, bot-core version needs to be bumped and then merged into main, then this branch will be updated
Closes #1089
This adds the support of bookmarking a message from a context menu, but preserves the old behavior as well.
To not lose the functionality of choosing a custom title, a modal has been added where a user is prompted for a title, which they can freely skip.
1. As usual, a user needs to identify a message to bookmark
2. A user hovers on the message, then clicks on the ellipsis (three dots) -> Apps -> Bookmark 
3. A user will be asked to choose a custom title for their bookmark, …
=> Make bookmark a context menu command

bot/exts/utilities/bookmark.py
uncaught typo in #1176 
noticed it the very first time I went to use the command.
=> fix typo in user-facing bookmark message

bot/exts/utilities/bookmark.py
This deprecates the text-based bookmark command, now that we have the context menu command.
Any users that invoke the old text-based command will be told how to use the new context menu command in sir-lance-playground.
This also simplifies a lot of the implementation of the bookmark cog.
I suggest reviewing commit-by-commit as some code has been moved around.
=> Deprecate bookmark text command

bot/exts/utilities/challenges.py
Closes #1170 
The issue mentioned two problems:
1. interactions edit the message but still show as failed
The problem is that discord automatically says the interaction failed if the bot doesn't respond to the interaction. Adding interaction.response.defer() fixes this. (See this stackoverflow discussion: https://stackoverflow.com/questions/71177867/discord-py-error-message-this-interaction-failed)
2. The same challenge seems to be shown every time for a given query, where it should be random.
I believe this happened because of the if statements that chose the kata_id. Whenever a query resulted in more than 3 katas, the first elif statement was called, resulting in the same 3 katas being displayed over and over. My solution is to remove the elif statements and always make a random …
=> fixed embed interaction and randomly choosing a kata

bot/constants.py, bot/exts/fun/latex.py
Closes #1207.
Adds the `#python-help` channel to the list of channels where `.latex` command is allowed.
=> Allow .latex in python-help channel

bot/exts/events/hacktoberfest/hacktoberstats.py, bot/exts/fun/movie.py, bot/exts/fun/snakes/__init__.py, bot/exts/holidays/halloween/scarymovie.py, bot/exts/holidays/halloween/spookygif.py, bot/exts/utilities/reddit.py, bot/exts/utilities/wolfram.py
We have a lot of Cogs that need some API key to function.
If the key isn't present, it would result in constant 401s.
This PR adds a change that won't load these Cogs & log a warning whenever these keys aren't present.
=> Run null check on needed API keys before loading cogs.

bot/exts/core/help.py
Closes #1266 
Fix extra space being added to command signature in `.help` command
=> Fix extra space in .help command signature

bot/exts/holidays/halloween/monstersurvey.py
Closes #1347 
Change parameter name from `name` to `title` in a call to `Embed` in monstersurvey.py.
=> Use title as parameter name for Embed in monster_vote

bot/exts/holidays/holidayreact.py
> Needs to match love, loves, lovelies, wuv, wuvs... quick, get Shenan in here.
> \- @Preocts, https://discord.com/channels/267624335836053506/267624335836053506/1078159856688713778
Added alternate spellings and misspellings to the February triggers in the holidayreact cog.
=> holidayreact: add alternate spellings to February

bot/exts/fun/snakes/_snakes_cog.py
Closes #1379 Solves SIR-LANCEBOT-AR
=> Remove usage of non-existent ctx.history.filter

bot/constants.py, poetry.lock, pyproject.toml
Currently this doesn't work due to https://github.com/pydantic/pydantic-settings/issues/106. A PR fixing that was merged so just waiting for a release.
=> Update to pydantic 2.0

.github/workflows/status_embed.yaml
It seems as if github is blocking wget's user agent.
We don't know why, but as of recently, Github has been unauthorizing these types of requests whenever we use wget.
=> Download pull request artifact using curl #1185

bot/resources/utilities/py_topics.yaml
Raised by @nedbat on [Discord](https://discord.com/channels/267624335836053506/385474242440986624/1192436157691220021) (requires PyDis Helpers role)
- Removed "What third-party library do you wish was in the Python standard library?" from topics
=> Remove "What third-party library do you wish was in the Python standard library?" from topics

bot/exts/utilities/rfc.py
Solves #1426 Soves SIR-LANCEBOT-BA
This was causing a pydantic validation error, was it was being passed a string.
The only place this is used internaly casts it to a string anyway, so no further changes were needed.
=> Correctly type revisions as an int

.gitpod.yml
- Closes #1437 and also closes #916.
- Use python 3.11 as required by poetry
- Fix poetry install error on workspace refresh
All relevant info is detailed in the linked issues.
1. Open gitpod workspace using this repo
2. Ensure auto-setup finishes successfully
3. Close workspace and wait for it to reset (not sure if there's a faster way, but this means wait for about 1hr before reopening)
4. Reopen workspace
5. Ensure auto-setup on workspace restart finishes successfully
I have tested the solution when writing the original issues but not after opening this PR, but it _should_ be fine. Additional testing details can also be found in #916.
=> Fix gitpod support

bot/resources/fun/trivia_quiz.json
Closes #1459 
Added questions to the trivia question json.
=> Add trivia questions

.github/CODEOWNERS
Updated [CODEOWNERS](https://github.com/python-discord/sir-lancebot/blob/main/.github/CODEOWNERS) via removing users that are no longer active on this repo.
=> Removed inactive users from `CODEOWNERS`

bot/constants.py, bot/exts/utilities/githubinfo.py
Closes #999.
Issues which are closed with reason "not-planned" will show up next to the correct icon as used by github. This emoji [has been added](https://discord.com/channels/267624335836053506/635950537262759947/1221642237004484739) to the emoji server.
Any other reasons for closing will use the completion icon.
=> Support issues closed as not-planned in GitHub Issue linking

.github/workflows/lint.yaml, .gitpod.yml, Dockerfile, bot/exts/fun/battleship.py, bot/exts/fun/connect_four.py, poetry.lock, pyproject.toml
This bumps lance up to Python 3.12.
=> Python 3.12

bot/log.py
There aren't any transactions currently, so this wont do much, but the experiment config will be removed in the future so we shouldn't use it, and this brings us more in line with bot's config.
=> Replace sentry experiment with standard version and add AsyncioIntegration

bot/exts/fun/uwu.py
add emoji
- [ x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ x] Read all the comments in this template?
- [x ] Ensure there is an issue open, or link relevant discord discussions?
- [x ] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?
=> better emojis replacement

bot/exts/utilities/colour.py
Closes #1650 
Made the user input title cased when looking up the name in the reference color list.
=> Adjust user input to title cased when looking up name
